### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 0: invalid start byte

### ISSUE THREAD

**Issue by jinxinkai** [randy3k/radian#107]
when run `radian` in `windows 10` by `Python 3.7.4`
throw:
```
Traceback (most recent call last):
  File "D:\soft\python37\Scripts\radian-script.py", line 11, in <module>
    load_entry_point('radian==0.4.0', 'console_scripts', 'radian')()
  File "d:\soft\python37\lib\site-packages\radian\__init__.py", line 75, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "d:\soft\python37\lib\site-packages\radian\radianapp.py", line 82, in run
    rchitect.init(args=args)
  File "d:\soft\python37\lib\site-packages\rchitect\setup.py", line 46, in init
    raise Exception(ffi.string(lib._libR_dl_error_message()).decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 0: invalid start byte
```

**Comment by randy3k** [comment]
An error message was triggered when radian failed to load the R shared library.
And this is a bug in handling the display of the error message.

The display bug has been in rchitect https://github.com/randy3k/rchitect/commit/d03e4a8066b136951abd63be6fa50220acebb564

Please make sure that your R is installed probably and the shared library exists.
