### ISSUE TITLE
radian crashes when interrupting long execution

### ISSUE THREAD

**Issue by renkun-ken** [randy3k/radian#116]
In the middle of a long execution (subsetting a `data.table` of 1e8 rows and tens of columns using `%in%`), I try to interrupt it with `Ctrl+C`, I press the key multiple times and radian crashes with the following stack trace:

```
unexpected error was caught.
please report to https://github.com/randy3k/radian for such error.

Traceback (most recent call last):
  File "/home/ken/.local/lib/python3.5/site-packages/radian/console.py", line 38, in read_console
    text = session.prompt(add_history=add_history)
  File "/home/ken/.local/lib/python3.5/site-packages/lineedit/prompt.py", line 236, in prompt
    result = super(ModalPromptSession, self).prompt(**kwargs)
  File "/home/ken/.local/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/shortcuts/prompt.py", line 731, in prompt
    return run_sync()
  File "/home/ken/.local/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/shortcuts/prompt.py", line 715, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run)
  File "/home/ken/.local/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/application/application.py", line 682, in run
    return run()
  File "/home/ken/.local/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/application/application.py", line 654, in run
    f = self.run_async(pre_run=pre_run)
  File "/home/ken/.local/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/application/application.py", line 513, in run_async
    assert not self._is_running
AssertionError
<class 'SystemExit'> 1
```

**Comment by randy3k** [comment]
Thank you for reporting it. I am guessing that one of the `ctrl+c`'s was sent to some important part of the python code instead of R and that stops the python code from running. It is also tricky to reproduce.

**Comment by randy3k** [comment]
It is caused by a different issue as in #118, more related to #35. I have also pushed a fix to rchitect. Hopefully, that will fix it.

**Comment by randy3k** [comment]
Spent a whole night tracking this issue. Finally I would return to languageserver.

**Comment by renkun-ken** [comment]
Thanks for your hard work! I'll test it on my production server with large amount of data and see if the problem still persists.

**Comment by renkun-ken** [comment]
I test it and it just works! Thanks again for your hard work!
