### ISSUE TITLE
AssertionError when readxl::read_excel

### ISSUE THREAD

**Issue by renkun-ken** [randy3k/radian#119]
When I read a excel xls file using `readxl::read_excel` with the following code:

```r
data <- readxl::read_excel("FY-2017-F-7-Notices.xlsx")
```

radian shows the following trace back messages:

```
From cffi callback <function cb_write_console_capturable at 0x7f32d8903f28>:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/rchitect/callbacks.py", line 182, in cb_write_console_capturable
    console.write_console(text, otype)
  File "/usr/lib64/python3.5/site-packages/rchitect/console.py", line 23, in write_console
    _callback.write_console_ex(buf, otype)
  File "/usr/lib/python3.5/site-packages/radian/console.py", line 85, in write_console_ex
    print_formatted_text(ANSI(stderr_format.format(buf)), end="", file=sys.stderr)
  File "/usr/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/shortcuts/utils.py", line 115, in print_formatted_text
    output, fragments, merged_style, color_depth=color_depth)
  File "/usr/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/renderer.py", line 642, in print_formatted_text
    assert '\r' not in text
AssertionError
-From cffi callback <function cb_write_console_capturable at 0x7f32d8903f28>:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/rchitect/callbacks.py", line 182, in cb_write_console_capturable
    console.write_console(text, otype)
  File "/usr/lib64/python3.5/site-packages/rchitect/console.py", line 23, in write_console
    _callback.write_console_ex(buf, otype)
  File "/usr/lib/python3.5/site-packages/radian/console.py", line 85, in write_console_ex
    print_formatted_text(ANSI(stderr_format.format(buf)), end="", file=sys.stderr)
  File "/usr/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/shortcuts/utils.py", line 115, in print_formatted_text
    output, fragments, merged_style, color_depth=color_depth)
  File "/usr/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/renderer.py", line 642, in print_formatted_text
    assert '\r' not in text
AssertionError
|From cffi callback <function cb_write_console_capturable at 0x7f32d8903f28>:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/rchitect/callbacks.py", line 182, in cb_write_console_capturable
    console.write_console(text, otype)
  File "/usr/lib64/python3.5/site-packages/rchitect/console.py", line 23, in write_console
    _callback.write_console_ex(buf, otype)
  File "/usr/lib/python3.5/site-packages/radian/console.py", line 85, in write_console_ex
    print_formatted_text(ANSI(stderr_format.format(buf)), end="", file=sys.stderr)
  File "/usr/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/shortcuts/utils.py", line 115, in print_formatted_text
    output, fragments, merged_style, color_depth=color_depth)
  File "/usr/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/renderer.py", line 642, in print_formatted_text
    assert '\r' not in text
AssertionError
From cffi callback <function cb_write_console_capturable at 0x7f32d8903f28>:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/rchitect/callbacks.py", line 182, in cb_write_console_capturable
    console.write_console(text, otype)
  File "/usr/lib64/python3.5/site-packages/rchitect/console.py", line 23, in write_console
    _callback.write_console_ex(buf, otype)
  File "/usr/lib/python3.5/site-packages/radian/console.py", line 85, in write_console_ex
    print_formatted_text(ANSI(stderr_format.format(buf)), end="", file=sys.stderr)
  File "/usr/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/shortcuts/utils.py", line 115, in print_formatted_text
    output, fragments, merged_style, color_depth=color_depth)
  File "/usr/lib/python3.5/site-packages/lineedit/deps/prompt_toolkit/renderer.py", line 642, in print_formatted_text
    assert '\r' not in text
AssertionError
```

The file is attached [here](https://1drv.ms/x/s!AnktoOHmK5VsgY4YWyzpE3un_d0MyQ?e=ZPTVK3).

**Comment by randy3k** [comment]
Thanks. I could reproduce it.

**Comment by randy3k** [comment]
9c392ac should fix this.

**Comment by renkun-ken** [comment]
Thanks for the quick fix! It works perfectly now.
