### ISSUE TITLE
Exception: cannot load R library

### ISSUE THREAD

**Issue by plutoese** [randy3k/radian#120]
While running radian, something goes wrong. 
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\radian.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\radian\__init__.py", line 76, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "c:\python\lib\site-packages\radian\radianapp.py", line 83, in run
    rchitect.init(args=args)
  File "c:\python\lib\site-packages\rchitect\setup.py", line 27, in init
    raise Exception("cannot load R library")
Exception: cannot load R library

**Comment by randy3k** [comment]
What version of R have you installed? Could you report the output of `radian --version`

**Comment by a-hurst** [comment]
Can confirm this is an issue with a fresh VM install of Windows 10, a fresh install of R 3.6.1, and Python 3.7.5 installed from the Microsoft Store:

```
C:\Users\austinhurst>python -m radian --version
radian version: 0.4.2
r executable: C:\Program Files\R\R-3.6.1\bin\R
r version: 3.6.1
python executable: C:\Users\austinhurst\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe
python version: 3.7.5
```

I get the same error as the user above:

```
C:\Users\austinhurst>python -m radian
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\austinhurst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\radian\__main__.py", line 16, in <module>
    main()
  File "C:\Users\austinhurst\AppData\Local\Packages\PythonSoftwareFoundation.Python.  File "C:\Users\austinhurst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\radian\radianapp.py", line 83, in run
    rchitect.init(args=args)  File "C:\Users\austinhurst\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\rchitect\setup.py", line 27, in init
    raise Exception("cannot load R library")
Exception: cannot load R library
```

However, I decided to try uninstalling the Microsoft Store python and re-installing from Python.org, and sure enough `radian` works perfectly fine. Maybe the way the MS store version is compiled has some weird problems with cffi behaviour? Anyway, for now the solution is apparently just to use the Python.org version of Python. @plutoese, how did you install Python on your system?

**Comment by randy3k** [comment]
I’ll take a look when I have a chance.

**Comment by randy3k** [comment]
I would reproduce the same error with Microsoft store python 3.7. (And I even couldn't `pip install radian` with Microsoft store python 3.8). I didn't dig too much for the exact reason why it failed, I am guessing that it is lacking some dynamic library which cffi requires.

**Comment by randy3k** [comment]
I finally figured out the reason why radian doesn't work with Microsoft Store python. It is because Microsoft Store apps are very conservative about DLLs searching path, i.e., it doesn't allow an app to search for DLLs outside of the system paths: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-windows-store-apps
Thus radian is not able to locate the `Rblas.dll` which is needed for opening `R.dll`. 

The bad news is, however, that there is virtually no fix because R relies on dynamical imports.

**Comment by diandian11** [comment]
I also has  the  same errror
![image](https://user-images.githubusercontent.com/31070013/71556842-36ad7180-2a78-11ea-82bd-605574b5aff2.png)
![image](https://user-images.githubusercontent.com/31070013/71556845-43ca6080-2a78-11ea-994c-6fe66d1ea8e0.png)

**Comment by randy3k** [comment]
Actually, it’s not the same error. In your case, radian even cannot locate the R shared library. I see that it is a 32bit python, do you also install a 32bit R?

**Comment by randy3k** [comment]
I came up with a workaround to support microsoft store python 9dba230803f2bc4d4ae408f75a7d96dddb0dcb73

**Comment by renkun-ken** [comment]
@randy3k Nice work. Will remove the Microsoft Store Python issue from https://github.com/Ikuyadeu/vscode-R/wiki/Installation:-Windows when it is released.

**Comment by randy3k** [comment]
v0.5.4 is out :)
