### ISSUE TITLE
error on radian launch 

### ISSUE THREAD

**Issue by Shyamniper** [randy3k/radian#121]
I am not able to launch radian post successful installation. 
I don't what information I should share to detail the error, I am on Raspbian os, using zsh shell with R version 3.5.2 Python 2.7.16 and Python 3.7.3 installed using sudo apt.
Installation was done using pip install -U radian
I have tried re-installation.

Traceback (most recent call last):
  File "/usr/local/bin/radian", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/radian/__init__.py", line 76, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/usr/local/lib/python2.7/dist-packages/radian/radianapp.py", line 83, in run
    rchitect.init(args=args)
  File "/usr/local/lib/python2.7/dist-packages/rchitect/setup.py", line 46, in init
    raise Exception(system2utf8(ffi.string(lib._libR_dl_error_message())))
Exception: (Unknown error)

**Comment by randy3k** [comment]
I think I will need to launch a Raspbian VM to check it. I haven never tested radian on any linux platforms other than Ubuntu.

**Comment by randy3k** [comment]
Could you check it works with the current master of rchitect? I believe that I have a [fix](https://github.com/randy3k/rchitect/commit/4836ba4e3f53480863ab456887e5c330f5caafe8)

```
pip3 install -U git+https://github.com/randy3k/rchitect
```

**Comment by Shyamniper** [comment]
It did not work, but then I reinstalled radian with pip3 install -U radian instead pip install -U radian, then I can launch radian. I don't know which combination worked, or I have messed up the environment.
I want to thank you for developing radian; I can use it on R running on termux app on android code completion is a big help; it allows me to work on small scripts while I am traveling.

**Comment by randy3k** [comment]
You might have installed two versions of radian. One for python2, another for python3.

**Comment by Shyamniper** [comment]
Yes python3 is working for me.

**Comment by statnmap** [comment]
I faced the same problem on raspbian with `pip install -U radian` and `pip install -U git+https://github.com/randy3k/radian`.  
I add the Traceback for others to find this issue too.
Installation is also successful with `pip3 install -U radian`

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/randy3k/radian
  Cloning https://github.com/randy3k/radian to /tmp/pip-req-build-peNJLe
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-peNJLe/setup.py", line 60, in <module>
        tests_require=tests_deps
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-wF4HrD/pytest-runner-5.3.1/setup.py", line 21, in <module>
        return re.search("__version__ = ['\"]([^'\"]+)['\"]", init_py).group(1)
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 44, in _execfile
        code = compile(script, filename, 'exec')
      File "/tmp/easy_install-wF4HrD/pytest-runner-5.3.1/temp/easy_install-S5xLLZ/setuptools_scm-6.3.2/setup.py", line 22
        f"{type(self).__name__} is forbidden, "
                                              ^
    SyntaxError: invalid syntax
```

**Comment by randy3k** [comment]
It seems to be an issue of setuptools.
