### ISSUE TITLE
Error on load reticulate

### ISSUE THREAD

**Issue by renkun-ken** [randy3k/radian#123]
When I load reticulate in radian, the following error occurs:

```
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Platform: x86_64-pc-linux-gnu (64-bit)

> library(reticulate)                                                                                                                                                                                
Error in py_config$config() : 
  /usr/bin/python3: cannot dynamically load executable
Error in fun(pkgname, pkgpath) : Error
The host python environment is /usr/bin/python3
and `radian` is forcing `reticulate` to use this version of python.
Any python packages needed, e.g., `tensorflow` and `keras`,
have to be available to the current python environment.

File an issue at https://github.com/randy3k/radian if you encounter any
difficulties in loading `reticulate`.
```

If I call `repl_python()`, radian crashes immediately.

```
$ r
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Platform: x86_64-pc-linux-gnu (64-bit)

> reticulate::repl_python()                                                                                                                                                                          
free(): invalid pointer
[1]    10516 abort (core dumped)  radian
```

Everything works with the original R terminal.

I'm using the latest radian and following is my session info:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.7.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.13

loaded via a namespace (and not attached):
[1] compiler_3.6.1  Matrix_1.2-17   tools_3.6.1     Rcpp_1.0.2      grid_3.6.1      jsonlite_1.6    lattice_0.20-38
```

**Comment by randy3k** [comment]
Could you run the following in python?

```r
import rchitect.py_config
rchitect.py_config.config()
```

**Comment by renkun-ken** [comment]
```
Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rchitect.py_config
>>> rchitect.py_config.config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/renkun/.local/lib/python3.7/site-packages/rchitect/py_config.py", line 45, in config
    lib = ctypes.PyDLL(libpython)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python3: cannot read file data: Is a directory
```

**Comment by randy3k** [comment]
That's strange. I do expect the same error `/usr/bin/python3: cannot dynamically load executable`.

I have pushed a commit https://github.com/randy3k/rchitect/commit/708bb60836f225e3da31100692d7a53873698671
Could you install and test the master branch of rchitect?

```
pip install git+https://github.com/randy3k/rchitect
```

**Comment by randy3k** [comment]
By the way, it is recommended to use miniconda/anaconda python distribution and radian and rchitect are well tested with miniconda's python.

**Comment by renkun-ken** [comment]
It looks good now with the latest fix.

```
>>> import rchitect.py_config
>>> rchitect.py_config.config()
('/usr/bin/python3', '', '/usr:/usr', True)
```

and reticulate works now. Thanks!

**Comment by randy3k** [comment]
How did you install your python? I believe that ubuntu default python3 is 3.5?

It is actually the first time I encounter this error, it has never occurred to me with the default python3 on Ubuntu.

**Comment by renkun-ken** [comment]
I'm using Ubuntu 19.10 and python is from the Ubuntu repository.

**Comment by randy3k** [comment]
Oh, I missed that. Let me spin up a Ubuntu 19.0 docker container and do some tests.

**Comment by renkun-ken** [comment]
That'd be very nice. Thanks again!

**Comment by randy3k** [comment]
I could reproduce it on Ubuntu 19.0 but I cannot figure out why it raises an OSError. Anyway it seems that the workaround in rchitect works for this particular distribution of python, so I'd declare that the issue is resolved.

**Comment by randy3k** [comment]
Ok. Given that there are some new commits around the error `cannot dynamically load executable` https://github.com/kraj/glibc/blob/7db1fe38de21831d53ceab9ae83493d8d1aec601/elf/dl-load.c#L1174, I believe that it is an issue of the recent version of glibc.
