### ISSUE TITLE
Error: "assert '\r' not in text" for package that writes to stderr

### ISSUE THREAD

**Issue by elbersb** [randy3k/radian#128]
First of all, thanks for radian!
I ran into the following problem: 

```py
#> library(segregation)                                                                                                                     
mutual_difference(schools00, schools05, group = "race", unit = "school",
#> mutual_difference(schools00, schools05, group = "race", unit = "school", 
                      weight = "n", method = "shapley")                                                                                      
[IPF 1/6] #From cffi callback <function cb_write_console_capturable at 0x10b916320>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rchitect/callbacks.py", line 182, in cb_write_console_capturable
    console.write_console(text, otype)
  File "/usr/local/lib/python3.7/site-packages/rchitect/console.py", line 23, in write_console
    _callback.write_console_ex(buf, otype)
  File "/usr/local/lib/python3.7/site-packages/radian/console.py", line 85, in write_console_ex
    print_formatted_text(ANSI(stderr_format.format(buf)), end="", file=sys.stderr)
  File "/usr/local/lib/python3.7/site-packages/lineedit/deps/prompt_toolkit/shortcuts/utils.py", line 115, in print_formatted_text
    output, fragments, merged_style, color_depth=color_depth)
  File "/usr/local/lib/python3.7/site-packages/lineedit/deps/prompt_toolkit/renderer.py", line 642, in print_formatted_text
    assert '\r' not in text
AssertionError
```

The package updates the output text continuously, and this might cause some trouble from radian. The relevant code is here: https://github.com/elbersb/segregation/blob/master/R/segregation.R#L27

**Comment by randy3k** [comment]
A similar bug was reported a while ago, could you check if the latest release fixed it?

**Comment by elbersb** [comment]
Yes, it works with the development version. Should've checked that first, sorry!

**Comment by randy3k** [comment]
No problem. The latest release v0.4.2 also contains the fix.
