### ISSUE TITLE
RuntimeError: Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by DoctorAnonymous** [randy3k/radian#155]
radian-0.4.6
macOS 10.15
python 3.7

When I run radian in my zsh terminal, radian reports the following error and exits.

```
Traceback (most recent call last):
  File "/usr/local/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/radian/__init__.py", line 88, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/usr/local/lib/python3.7/site-packages/radian/radianapp.py", line 106, in run
    reticulate.configure()
  File "/usr/local/lib/python3.7/site-packages/radian/reticulate/__init__.py", line 41, in configure
    if package_is_installed("reticulate") and roption("radian.enable_reticulate_prompt", True):
  File "/usr/local/lib/python3.7/site-packages/radian/rutils.py", line 26, in package_is_installed
    return pkg in rcopy(reval("rownames(installed.packages())"))
  File "/usr/local/lib/python3.7/site-packages/rchitect/interface.py", line 163, in reval
    return box(reval_p(s, envir=envir))
  File "/usr/local/lib/python3.7/site-packages/rchitect/dispatch.py", line 53, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rchitect/interface.py", line 159, in reval_p
    return reval_p(rparse_p(s), envir=envir)
  File "/usr/local/lib/python3.7/site-packages/rchitect/dispatch.py", line 53, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rchitect/interface.py", line 146, in reval_p
    raise RuntimeError("{}".format(err))
RuntimeError: Error: $ operator is invalid for atomic vectors
```

Funny error because I have been running radian for months and I got this error this morning.
Reinstall in pip does not work.
Happy to provide more information and grateful for your contribution in this useful tool.

**Comment by randy3k** [comment]
it looks like an issue of `rownames(installed.packages())`.

Does it work in plain R?

**Comment by DoctorAnonymous** [comment]
You're right. I think something's wrong with  R and I cannot fix it. So I reinstalled R. Sorry to bother you.
