### ISSUE TITLE
can't start new thread

### ISSUE THREAD

**Issue by r4ulmn** [randy3k/radian#197]
I got this error when creating a big list:

r$> unexpected error was caught.
please report to https://github.com/randy3k/radian for such error.
can't start new thread
Traceback (most recent call last):
  File "C:\Users\raul\AppData\Roaming\Python\Python38\site-packages\radian\console.py", line 96, in read_conso
le
    text = session.prompt(add_history=add_history)
  File "C:\Users\raul\AppData\Roaming\Python\Python38\site-packages\lineedit\prompt.py", line 231, in prompt
    result = super(ModalPromptSession, self).prompt(**kwargs)
  File "C:\Users\raul\AppData\Roaming\Python\Python38\site-packages\lineedit\deps\prompt_toolkit\shortcuts\pro
mpt.py", line 797, in prompt
    return run_sync()
  File "C:\Users\raul\AppData\Roaming\Python\Python38\site-packages\lineedit\deps\prompt_toolkit\shortcuts\pro
mpt.py", line 786, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "C:\Users\raul\AppData\Roaming\Python\Python38\site-packages\lineedit\deps\prompt_toolkit\application\a
pplication.py", line 736, in run
    return run()
  File "C:\Users\raul\AppData\Roaming\Python\Python38\site-packages\lineedit\deps\prompt_toolkit\application\a
pplication.py", line 709, in run
    run_until_complete(f, inputhook=inputhook)
  File "C:\Users\raul\AppData\Roaming\Python\Python38\site-packages\lineedit\deps\prompt_toolkit\eventloop\def
aults.py", line 126, in run_until_complete
    return get_event_loop().run_until_complete(future, inputhook=inputhook)
  File "C:\Users\raul\AppData\Roaming\Python\Python38\site-packages\lineedit\deps\prompt_toolkit\eventloop\win
32.py", line 67, in run_until_complete
    self._run_once(inputhook)
  File "C:\Users\raul\AppData\Roaming\Python\Python38\site-packages\lineedit\deps\prompt_toolkit\eventloop\win
32.py", line 86, in _run_once
    self._inputhook_context.call_inputhook(ready, inputhook)
  File "C:\Users\raul\AppData\Roaming\Python\Python38\site-packages\lineedit\deps\prompt_toolkit\eventloop\inp
uthook.py", line 81, in call_inputhook
    threading.Thread(target=thread).start()
  File "c:\program files (x86)\python38-32\lib\threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by randy3k** [comment]
would you mind reporting how the error triggered?

**Comment by r4ulmn** [comment]
Sure,

I am saving some linear models in a nested list, something like this:
my_list <- list()
for(Iterator A ){
my_list[A] <- list()
for(Iterator B){
my_list[A][B] <- lm(some linear model)
}
}
The object my_list is king of big, saved in disk is about 500 MB. The code runs normal in R terminal. I search for a log file but didn't find anything.

**Comment by randy3k** [comment]
Is it during execution or while you are typing?

**Comment by r4ulmn** [comment]
during execution

**Comment by randy3k** [comment]
and what version of radian are you running on?

**Comment by r4ulmn** [comment]
radian version: 0.5.4
r executable: C:\PROGRA~1\R\R-40~1.0\bin\R
r version: 4.0.0
python executable: c:\program files (x86)\python38-32\python.exe
python version: 3.8.3

OK. Maybe later I will try to catch the exact line when the error occurs. Thank you.
