### ISSUE TITLE
Radian does not start on Big Sur 11.2

### ISSUE THREAD

**Issue by MikhailArkhipov** [randy3k/radian#259]
1. MacOS Big Sur 11.2 on M1, brand new clean laptop
2. R 4.0.3 installed from https://cran.r-project.org/bin/macosx/
3. Python 3.9.1 installed via python.org installer with universal binaries
4. Radian installed via pip3

- R.app runs normally
- Attempt to start radian fails with
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/radian", line 33, in <module>
    sys.exit(load_entry_point('radian==0.5.10', 'console_scripts', 'radian')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/radian/__init__.py", line 44, in main
    r_home = Rhome()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rchitect/utils.py", line 69, in Rhome
    raise RuntimeError("R_HOME ({}) does not exist.".format(rhome))
RuntimeError: R_HOME (/usr/local/lib/R) does not exist.
```
`/usr/local/lib/R` indeed does not exist on MacOS 11.2
R is in `/Library/Frameworks/R.framework/Versions/Current`

Attempt to set 
```
env R_HOME=/Library/Frameworks/R.framework/Versions/Current radian
```
then fails with
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/radian", line 33, in <module>
    sys.exit(load_entry_point('radian==0.5.10', 'console_scripts', 'radian')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/radian/__init__.py", line 101, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/radian/radianapp.py", line 94, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: dlopen(/Library/Frameworks/R.framework/Versions/Current/lib/libR.dylib, 10): image not found
```
since library is in `/Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib`

The only thing that works is setting
```
R_HOME=/Library/Frameworks/R.framework/Versions/Current/Resources radian
```

**Comment by Johnnypark99** [comment]
`R_HOME=/Library/Frameworks/R.framework/Versions/Current/Resources radian` doesn't work for me as well. Are there any other ways that worked?

**Comment by adamaltmejd** [comment]
Only thing that worked for me was building R from source (with homebrew) to ensure its M1 native and not through Rosetta.
