### ISSUE TITLE
Trying to run radian via comand console failed

### ISSUE THREAD

**Issue by duytrung** [randy3k/radian#266]
Hi Randy,

I tried to install radian via pip and it did install the package. However, when I tried to run radian it showed me this message:

```
C:\Anaconda\RRR>radian
Traceback (most recent call last):
  File "c:\anaconda\binaries\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\anaconda\binaries\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\Binaries\Scripts\radian.exe\__main__.py", line 7, in <module>
  File "c:\anaconda\binaries\lib\site-packages\radian\__init__.py", line 101, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "c:\anaconda\binaries\lib\site-packages\radian\radianapp.py", line 94, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "c:\anaconda\binaries\lib\site-packages\rchitect\setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: The specified module could not be found.

```
RRR is a folder in side my Anaconda package.

Here is the package list with default conda channel:
```

C:\Anaconda\RRR>conda list
# packages in environment at C:\Anaconda\Binaries:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
_r-mutex                  1.0.0               anacondar_1
alabaster                 0.7.12             pyhd3eb1b0_0
anaconda                  custom                   py38_1
anaconda-client           1.7.2                    py38_0
anaconda-navigator        1.10.0                   py38_0
anaconda-project          0.9.1              pyhd3eb1b0_1
appdirs                   1.4.4                      py_0
argh                      0.26.2                   py38_0
argon2-cffi               20.1.0           py38h2bbff1b_1
asn1crypto                1.4.0                      py_0
astroid                   2.5              py38haa95532_1
astropy                   4.2              py38h2bbff1b_0
async_generator           1.10               pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     20.3.0             pyhd3eb1b0_0
autopep8                  1.5.5              pyhd3eb1b0_0
babel                     2.9.0              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
backports                 1.0                pyhd3eb1b0_2
backports.functools_lru_cache 1.6.1              pyhd3eb1b0_0
backports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3
backports.tempfile        1.0                pyhd3eb1b0_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.2.0            py38he774522_0
beautifulsoup4            4.9.3              pyha847dfd_0
bitarray                  1.7.1            py38h2bbff1b_1
bkcharts                  0.2                      py38_0
black                     19.10b0                    py_0
blas                      1.0                         mkl
bleach                    3.3.0              pyhd3eb1b0_0
blosc                     1.21.0               h19a0ad4_0
bokeh                     2.3.0            py38haa95532_0
boto                      2.49.0                   py38_0
bottleneck                1.3.2            py38h2a96729_1
brotli                    1.0.9                ha925a31_2
brotlipy                  0.7.0           py38h2bbff1b_1003
bzip2                     1.0.8                he774522_0
ca-certificates           2021.1.19            haa95532_1
certifi                   2020.12.5        py38haa95532_0
cffi                      1.14.5           py38hcd4344a_0
chardet                   4.0.0           py38haa95532_1003
charls                    2.1.0                h33f27b4_2
click                     7.1.2              pyhd3eb1b0_0
cloudpickle               1.6.0                      py_0
clyent                    1.2.2                    py38_1
colorama                  0.4.4              pyhd3eb1b0_0
comtypes                  1.1.9           py38haa95532_1002
conda                     4.9.2            py38haa95532_0
conda-build               3.21.4           py38haa95532_0
conda-env                 2.6.0                         1
conda-package-handling    1.7.2            py38h76e460a_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
contextlib2               0.6.0.post1                py_0
cryptography              3.4.6            py38h71e12ea_0
curl                      7.71.1               h2a8f88b_1
cycler                    0.10.0                   py38_0
cython                    0.29.22          py38hd77b12b_0
cytoolz                   0.11.0           py38he774522_0
dask                      2021.3.0           pyhd3eb1b0_0
dask-core                 2021.3.0           pyhd3eb1b0_0
decorator                 4.4.2              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713                   py_0
distributed               2021.3.0         py38haa95532_0
docutils                  0.16                     py38_1
entrypoints               0.3                      py38_0
et_xmlfile                1.0.1                   py_1001
fastcache                 1.1.0            py38he774522_0
filelock                  3.0.12             pyhd3eb1b0_1
flake8                    3.8.4                      py_0
flask                     1.1.2              pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
fsspec                    0.8.3                      py_0
future                    0.18.2                   py38_1
get_terminal_size         1.0.0                h38e98db_0
gevent                    21.1.1           py38h2bbff1b_1
giflib                    5.2.1                h62dcd97_0
glob2                     0.7                pyhd3eb1b0_0
gmpy2                     2.0.8            py38h7edee0f_3
greenlet                  1.0.0            py38hd77b12b_2
h5py                      2.10.0           py38h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1                      py_0
html5lib                  1.1                        py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10               pyhd3eb1b0_0
imagecodecs               2021.1.11        py38h5da4933_1
imageio                   2.9.0                      py_0
imagesize                 1.2.0              pyhd3eb1b0_0
importlib-metadata        2.0.0                      py_1
importlib_metadata        2.0.0                         1
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2020.2                      254
intervaltree              3.1.0                      py_0
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.21.0           py38hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.3              pyhd3eb1b0_1
isort                     5.7.0              pyhd3eb1b0_0
itsdangerous              1.1.0              pyhd3eb1b0_0
jdcal                     1.4.1                      py_0
jedi                      0.17.2           py38haa95532_1
jinja2                    2.11.3             pyhd3eb1b0_0
joblib                    1.0.1              pyhd3eb1b0_0
jpeg                      9b                   hb83a4c4_2
json5                     0.9.5                      py_0
jsonschema                3.2.0                      py_2
jupyter                   1.0.0                    py38_7
jupyter_client            6.1.7                      py_0
jupyter_console           6.2.0                      py_0
jupyter_core              4.7.1            py38haa95532_0
jupyterlab                2.2.6                      py_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         1.2.0                      py_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
keyring                   22.3.0           py38haa95532_0
kiwisolver                1.3.1            py38hd77b12b_0
krb5                      1.18.2               hc04afaa_0
lazy-object-proxy         1.5.2            py38h2bbff1b_0
lcms2                     2.11                 hc51a39a_0
lerc                      2.2.1                hd77b12b_0
libaec                    1.0.4                h33f27b4_1
libarchive                3.4.2                h5e25573_0
libcurl                   7.71.1               h2a8f88b_1
libdeflate                1.7                  h2bbff1b_5
libiconv                  1.15                 h1df5818_7
liblief                   0.10.1               ha925a31_0
libllvm9                  9.0.1                h21ff451_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.2.0                he0120a3_0
libxml2                   2.9.10               hb89e7f3_3
libxslt                   1.1.34               he774522_0
libzopfli                 1.0.3                ha925a31_0
lineedit                  0.1.6                    pypi_0    pypi
llvmlite                  0.35.0           py38h34b8924_4
locket                    0.2.1            py38haa95532_1
lxml                      4.6.2            py38h9b66d53_0
lz4-c                     1.9.3                h2bbff1b_0
lzo                       2.10                 he774522_2
m2w64-bwidget             1.9.10                        2
m2w64-bzip2               1.0.6                         6
m2w64-expat               2.1.1                         2
m2w64-fftw                3.3.4                         6
m2w64-flac                1.3.1                         3
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-gsl                 2.1                           2
m2w64-libiconv            1.14                          6
m2w64-libjpeg-turbo       1.4.2                         3
m2w64-libogg              1.3.2                         3
m2w64-libpng              1.6.21                        2
m2w64-libsndfile          1.0.26                        2
m2w64-libsodium           1.0.10                        2
m2w64-libtiff             4.0.6                         2
m2w64-libvorbis           1.3.5                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-libxml2             2.9.3                         4
m2w64-mpfr                3.1.4                         4
m2w64-openblas            0.2.19                        1
m2w64-pcre                8.38                          2
m2w64-speex               1.2rc2                        3
m2w64-speexdsp            1.2rc3                        3
m2w64-tcl                 8.6.5                         3
m2w64-tk                  8.6.5                         3
m2w64-tktable             2.10                          5
m2w64-wineditline         2.101                         5
m2w64-xz                  5.2.2                         2
m2w64-zeromq              4.1.4                         2
m2w64-zlib                1.2.8                        10
markdown                  3.3.4            py38haa95532_0
markupsafe                1.1.1            py38he774522_0
matplotlib                3.3.4            py38haa95532_0
matplotlib-base           3.3.4            py38h49ac443_0
mccabe                    0.6.1                    py38_1
menuinst                  1.4.16           py38he774522_1
mistune                   0.8.4           py38he774522_1000
mkl                       2020.2                      256
mkl-service               2.3.0            py38h196d8e1_0
mkl_fft                   1.3.0            py38h46781fe_0
mkl_random                1.1.1            py38h47e9c7a_0
mock                      4.0.3              pyhd3eb1b0_0
more-itertools            8.7.0              pyhd3eb1b0_0
mpc                       1.1.0                h7edee0f_1
mpfr                      4.0.2                h62dcd97_1
mpir                      3.0.0                hec2e145_1
mpmath                    1.1.0                    py38_0
msgpack-python            1.0.2            py38h59b6b97_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py38_0
mypy_extensions           0.4.3                    py38_0
navigator-updater         0.2.1                    py38_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.0.7                    py38_0
nbformat                  5.1.2              pyhd3eb1b0_1
nest-asyncio              1.5.1              pyhd3eb1b0_0
networkx                  2.5                        py_0
nltk                      3.5                        py_0
nose                      1.3.7           pyhd3eb1b0_1006
notebook                  6.2.0            py38haa95532_0
numba                     0.52.0           py38hf11a4ad_0
numexpr                   2.7.3            py38hcbcaa1e_0
numpy                     1.19.2           py38hadc3359_0
numpy-base                1.19.2           py38ha3acd2a_0
numpydoc                  1.1.0              pyhd3eb1b0_1
olefile                   0.46                       py_0
openjpeg                  2.3.0                h5ec785f_1
openpyxl                  3.0.7              pyhd3eb1b0_0
openssl                   1.1.1j               h2bbff1b_0
packaging                 20.9               pyhd3eb1b0_0
pandas                    1.2.3            py38hf11a4ad_0
pandoc                    2.11                 h9490d1a_0
pandocfilters             1.4.3            py38haa95532_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0
path                      15.1.2           py38haa95532_0
path.py                   12.5.0                        0
pathlib2                  2.3.5            py38haa95532_2
pathspec                  0.7.0                      py_0
pathtools                 0.1.2                      py_1
patsy                     0.5.1                    py38_0
pep8                      1.7.1                    py38_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.1.2            py38h4fa10fc_0
pip                       21.0.1           py38haa95532_0
pkginfo                   1.7.0            py38haa95532_0
pluggy                    0.13.1                   py38_0
ply                       3.11                     py38_0
powershell_shortcut       0.0.1                         3
prometheus_client         0.9.0              pyhd3eb1b0_0
prompt-toolkit            3.0.8                      py_0
prompt_toolkit            3.0.8                         0
psutil                    5.8.0            py38h2bbff1b_1
ptyprocess                0.7.0              pyhd3eb1b0_2
py                        1.10.0             pyhd3eb1b0_0
py-lief                   0.10.1           py38ha925a31_0
pycodestyle               2.6.0              pyhd3eb1b0_0
pycosat                   0.6.3            py38h2bbff1b_0
pycparser                 2.20                       py_2
pycurl                    7.43.0.6         py38h7a1dbc1_0
pydocstyle                5.1.1                      py_0
pyerfa                    1.7.2            py38h2bbff1b_0
pyflakes                  2.2.0              pyhd3eb1b0_0
pygments                  2.8.1              pyhd3eb1b0_0
pylint                    2.7.2            py38haa95532_1
pyls-black                0.4.6                hd3eb1b0_0
pyls-spyder               0.3.2              pyhd3eb1b0_0
pynacl                    1.4.0            py38h62dcd97_1
pyodbc                    4.0.30           py38ha925a31_0
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py38ha925a31_4
pyreadline                2.1                      py38_1
pyrsistent                0.17.3           py38he774522_0
pysocks                   1.7.1            py38haa95532_0
pytables                  3.6.1            py38ha5be198_0
pytest                    6.2.2            py38haa95532_2
python                    3.8.8                hdbf39b2_4
python-dateutil           2.8.1              pyhd3eb1b0_0
python-jsonrpc-server     0.4.0                      py_0
python-language-server    0.36.2             pyhd3eb1b0_0
python-libarchive-c       2.9                pyhd3eb1b0_0
pytz                      2021.1             pyhd3eb1b0_0
pywavelets                1.1.1            py38he774522_2
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7                    py38_0
pyyaml                    5.4.1            py38h2bbff1b_1
pyzmq                     20.0.0           py38hd77b12b_1
qdarkstyle                2.8.1                      py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 1.0.1                      py_0
qtconsole                 5.0.2              pyhd3eb1b0_0
qtpy                      1.9.0                      py_0
r-askpass                 1.0                       r36_0
r-assertthat              0.2.1             r36h6115d3f_0
r-backports               1.1.4             r36h6115d3f_0
r-base                    3.6.1                hf18239d_1
r-base64enc               0.1_3             r36h6115d3f_4
r-bh                      1.69.0_1          r36h6115d3f_0
r-boot                    1.3_20            r36h6115d3f_0
r-broom                   0.5.2             r36h6115d3f_0
r-callr                   3.2.0             r36h6115d3f_0
r-caret                   6.0_83            r36h6115d3f_0
r-cellranger              1.1.0             r36h6115d3f_0
r-class                   7.3_15            r36h6115d3f_0
r-cli                     1.1.0             r36h6115d3f_0
r-clipr                   0.6.0             r36h6115d3f_0
r-cluster                 2.0.8             r36h6115d3f_0
r-codetools               0.2_16            r36h6115d3f_0
r-colorspace              1.4_1             r36h6115d3f_0
r-crayon                  1.3.4             r36h6115d3f_0
r-curl                    3.3               r36h6115d3f_0
r-data.table              1.12.2            r36h6115d3f_0
r-dbi                     1.0.0             r36h6115d3f_0
r-dbplyr                  1.4.0             r36h6115d3f_0
r-dichromat               2.0_0             r36h6115d3f_4
r-digest                  0.6.18            r36h6115d3f_0
r-dplyr                   0.8.0.1           r36h6115d3f_0
r-ellipsis                0.1.0             r36h6115d3f_0
r-essentials              3.6.0                     r36_0
r-evaluate                0.13              r36h6115d3f_0
r-fansi                   0.4.0             r36h6115d3f_0
r-forcats                 0.4.0             r36h6115d3f_0
r-foreach                 1.4.4             r36h6115d3f_0
r-foreign                 0.8_71            r36h6115d3f_0
r-formatr                 1.6               r36h6115d3f_0
r-fs                      1.2.7             r36h6115d3f_0
r-generics                0.0.2             r36h6115d3f_0
r-ggplot2                 3.1.1             r36h6115d3f_0
r-glmnet                  2.0_16            r36h6115d3f_0
r-glue                    1.3.1             r36h6115d3f_0
r-gower                   0.2.0             r36h6115d3f_0
r-gtable                  0.3.0             r36h6115d3f_0
r-haven                   2.1.0             r36h6115d3f_0
r-hexbin                  1.27.2            r36h6115d3f_0
r-highr                   0.8               r36h6115d3f_0
r-hms                     0.4.2             r36h6115d3f_0
r-htmltools               0.3.6             r36h6115d3f_0
r-htmlwidgets             1.3               r36h6115d3f_0
r-httpuv                  1.5.1             r36h6115d3f_0
r-httr                    1.4.0             r36h6115d3f_0
r-ipred                   0.9_8             r36h6115d3f_0
r-irdisplay               0.7.0             r36h6115d3f_0
r-irkernel                0.8.15                    r36_0
r-iterators               1.0.10            r36h6115d3f_0
r-jsonlite                1.6               r36h6115d3f_0
r-kernsmooth              2.23_15           r36h6115d3f_4
r-knitr                   1.22              r36h6115d3f_0
r-labeling                0.3               r36h6115d3f_4
r-later                   0.8.0             r36h6115d3f_0
r-lattice                 0.20_38           r36h6115d3f_0
r-lava                    1.6.5             r36h6115d3f_0
r-lazyeval                0.2.2             r36h6115d3f_0
r-lubridate               1.7.4             r36h6115d3f_0
r-magrittr                1.5               r36h6115d3f_4
r-maps                    3.3.0             r36h6115d3f_0
r-markdown                0.9               r36h6115d3f_0
r-mass                    7.3_51.3          r36h6115d3f_0
r-matrix                  1.2_17            r36h6115d3f_0
r-mgcv                    1.8_28            r36h6115d3f_0
r-mime                    0.6               r36h6115d3f_0
r-modelmetrics            1.2.2             r36h6115d3f_0
r-modelr                  0.1.4             r36h6115d3f_0
r-munsell                 0.5.0             r36h6115d3f_0
r-nlme                    3.1_139           r36h6115d3f_0
r-nnet                    7.3_12            r36h6115d3f_0
r-numderiv                2016.8_1          r36h6115d3f_0
r-openssl                 1.3               r36h6115d3f_0
r-pbdzmq                  0.3_3             r36h6115d3f_0
r-pillar                  1.3.1             r36h6115d3f_0
r-pkgconfig               2.0.2             r36h6115d3f_0
r-plogr                   0.2.0             r36h6115d3f_0
r-plyr                    1.8.4             r36h6115d3f_0
r-prettyunits             1.0.2             r36h6115d3f_0
r-processx                3.3.0             r36h6115d3f_0
r-prodlim                 2018.04.18        r36h6115d3f_0
r-progress                1.2.0             r36h6115d3f_0
r-promises                1.0.1             r36h6115d3f_0
r-ps                      1.3.0             r36h6115d3f_0
r-purrr                   0.3.2             r36h6115d3f_0
r-quantmod                0.4_14            r36h6115d3f_0
r-r6                      2.4.0             r36h6115d3f_0
r-randomforest            4.6_14            r36h6115d3f_0
r-rbokeh                  0.6.3                     r36_0
r-rcolorbrewer            1.1_2             r36h6115d3f_0
r-rcpp                    1.0.1             r36h6115d3f_0
r-rcpproll                0.3.0             r36h6115d3f_0
r-readr                   1.3.1             r36h6115d3f_0
r-readxl                  1.3.1             r36h6115d3f_0
r-recipes                 0.1.5             r36h6115d3f_0
r-recommended             3.6.0                     r36_0
r-rematch                 1.0.1             r36h6115d3f_0
r-repr                    0.19.2            r36h6115d3f_0
r-reprex                  0.2.1             r36h6115d3f_0
r-reshape2                1.4.3             r36h6115d3f_0
r-rlang                   0.3.4             r36h6115d3f_0
r-rmarkdown               1.12              r36h6115d3f_0
r-rpart                   4.1_15            r36h6115d3f_0
r-rstudioapi              0.10              r36h6115d3f_0
r-rvest                   0.3.3             r36h6115d3f_0
r-scales                  1.0.0             r36h6115d3f_0
r-selectr                 0.4_1             r36h6115d3f_0
r-shiny                   1.3.2             r36h6115d3f_0
r-sourcetools             0.1.7             r36h6115d3f_0
r-spatial                 7.3_11            r36h6115d3f_4
r-squarem                 2017.10_1         r36h6115d3f_0
r-stringi                 1.4.3             r36h6115d3f_0
r-stringr                 1.4.0             r36h6115d3f_0
r-survival                2.44_1.1          r36h6115d3f_0
r-sys                     3.2               r36h6115d3f_0
r-tibble                  2.1.1             r36h6115d3f_0
r-tidyr                   0.8.3             r36h6115d3f_0
r-tidyselect              0.2.5             r36h6115d3f_0
r-tidyverse               1.2.1             r36h6115d3f_0
r-timedate                3043.102          r36h6115d3f_0
r-tinytex                 0.12              r36h6115d3f_0
r-ttr                     0.23_4            r36h6115d3f_0
r-utf8                    1.1.4             r36h6115d3f_0
r-uuid                    0.1_2             r36h6115d3f_4
r-viridislite             0.3.0             r36h6115d3f_0
r-whisker                 0.3_2             r36h6115d3f_4
r-withr                   2.1.2             r36h6115d3f_0
r-xfun                    0.6               r36h6115d3f_0
r-xml2                    1.2.0             r36h6115d3f_0
r-xtable                  1.8_4             r36h6115d3f_0
r-xts                     0.11_2            r36h6115d3f_0
r-yaml                    2.2.0             r36h6115d3f_0
r-zoo                     1.8_5             r36h6115d3f_0
radian                    0.5.10                   pypi_0    pypi
rchitect                  0.3.30                   pypi_0    pypi
regex                     2020.11.13       py38h2bbff1b_0
requests                  2.25.1             pyhd3eb1b0_0
rope                      0.18.0                     py_0
rtree                     0.9.4            py38h21ff451_1
ruamel_yaml               0.15.87          py38he774522_1
scikit-image              0.17.2           py38h1e1f486_0
scikit-learn              0.24.1           py38hf11a4ad_0
scipy                     1.6.1            py38h14eb087_0
seaborn                   0.11.1             pyhd3eb1b0_0
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                52.0.0           py38haa95532_0
simplegeneric             0.8.1                    py38_2
singledispatch            3.6.1           pyhd3eb1b0_1001
sip                       4.19.13          py38ha925a31_0
six                       1.15.0           py38haa95532_0
snappy                    1.1.8                h33f27b4_0
snowballstemmer           2.1.0              pyhd3eb1b0_0
sortedcollections         2.1.0              pyhd3eb1b0_0
sortedcontainers          2.3.0              pyhd3eb1b0_0
soupsieve                 2.2                pyhd3eb1b0_0
sphinx                    3.5.2              pyhd3eb1b0_0
sphinxcontrib             1.0                      py38_1
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0
sphinxcontrib-websupport  1.2.4                      py_0
spyder                    4.2.3            py38haa95532_0
spyder-kernels            1.10.2           py38haa95532_0
sqlalchemy                1.3.23           py38h2bbff1b_0
sqlite                    3.35.0               h2bbff1b_0
statsmodels               0.12.2           py38h2bbff1b_0
sympy                     1.7.1            py38haa95532_0
tbb                       2020.3               h74a9793_0
tblib                     1.7.0                      py_0
terminado                 0.9.2            py38haa95532_0
testpath                  0.4.4              pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
three-merge               0.1.1              pyhd3eb1b0_0
tifffile                  2021.3.5           pyhd3eb1b0_1
tk                        8.6.10               he774522_0
toml                      0.10.1                     py_0
toolz                     0.11.1             pyhd3eb1b0_0
tornado                   6.1              py38h2bbff1b_0
tqdm                      4.59.0             pyhb85f177_0
traitlets                 5.0.5              pyhd3eb1b0_0
typed-ast                 1.4.2            py38h2bbff1b_1
typing_extensions         3.7.4.3            pyha847dfd_0
ujson                     4.0.2            py38hd77b12b_0
unicodecsv                0.14.1                   py38_0
urllib3                   1.26.3             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  1.0.2            py38haa95532_1
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
werkzeug                  1.0.1              pyhd3eb1b0_0
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    py38_0
win_inet_pton             1.1.0            py38haa95532_0
win_unicode_console       0.5                      py38_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
wrapt                     1.12.1           py38he774522_1
xlrd                      2.0.1              pyhd3eb1b0_0
xlsxwriter                1.3.7              pyhd3eb1b0_0
xlwings                   0.23.0           py38haa95532_0
xlwt                      1.3.0                    py38_0
xmltodict                 0.12.0                     py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
zeromq                    4.3.3                ha925a31_3
zfp                       0.5.5                hd77b12b_4
zict                      2.0.0              pyhd3eb1b0_0
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
zope                      1.0                      py38_1
zope.event                4.5.0                    py38_0
zope.interface            5.2.0            py38h2bbff1b_0
zstd                      1.4.5                h04227a9_0

C:\Anaconda\RRR>
```
Thank you for consider the issue

**Comment by zoujx1024** [comment]
我也遇到这个问题，win10，怎么解决啊

**Comment by jimbrig** [comment]
try specifying the r-binary path with `radian --r-binary=R` and see if the problem persists.
