### ISSUE TITLE
cannot load shared library, image not found 

### ISSUE THREAD

**Issue by elvinwangyh** [randy3k/radian#273]
I tried to setup radian and received the following error:
```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/radian", line 33, in <module>
    sys.exit(load_entry_point('radian==0.5.10', 'console_scripts', 'radian')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/radian/__init__.py", line 101, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/radian/radianapp.py", line 94, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: dlopen(/Library/Frameworks/R.framework/Resources/library/lib/libR.dylib, 10): image not found
```

**Comment by randy3k** [comment]
It seems you have a wrong value of `R_HOME`.

**Comment by elvinwangyh** [comment]
thanks for the help, the issue is fixed
