### ISSUE TITLE
radian crash

### ISSUE THREAD

**Issue by jatom-tech** [randy3k/radian#287]
Hello 
I use radian for executing R within vs code and it is failing. I hope you can help.

My errors are like the following:

![image](https://user-images.githubusercontent.com/76389817/121694523-78927200-caca-11eb-90e2-5f6539034b37.png)

<img width="764" alt="Screen Shot 2021-06-11 at 15 35 59" src="https://user-images.githubusercontent.com/76389817/121694823-c3ac8500-caca-11eb-89d8-63b5bf756ccd.png">

**Comment by randy3k** [comment]
I think that you didn't activate the right condo environment. radian is install in the base of anaconda but you have activated a virtual environment.

**Comment by jatom-tech** [comment]
Thanks for info, but leaving the VE theres still an issue

See pic.

**Comment by randy3k** [comment]
Ya, you have to activate the base anaconda env.

**Comment by jatom-tech** [comment]
yes i am not so experienced in python vs code  and radian, but still the same

**Comment by jatom-tech** [comment]
Trying to start radian  gives me this

(base) Jans-MacBook-Pro:my_rvs janthomsen$ conda deactivate
Jans-MacBook-Pro:my_rvs janthomsen$ conda activate
(base) Jans-MacBook-Pro:my_rvs janthomsen$ radian
Traceback (most recent call last):
  File "/Users/janthomsen/opt/anaconda3/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/Users/janthomsen/opt/anaconda3/lib/python3.8/site-packages/radian/__init__.py", line 101, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/Users/janthomsen/opt/anaconda3/lib/python3.8/site-packages/radian/radianapp.py", line 94, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/Users/janthomsen/opt/anaconda3/lib/python3.8/site-packages/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: dlopen(/Users/janthomsen/opt/anaconda3/lib/R/lib/libR.dylib, 10): Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /Users/janthomsen/opt/anaconda3/lib/R/lib/libR.dylib
  Reason: image not found
(base) Jans-MacBook-Pro:my_rvs janthomsen$

**Comment by jatom-tech** [comment]
executing R from vs code


(base) Jans-MacBook-Pro:my_rvs janthomsen$ conda deactivate
Jans-MacBook-Pro:my_rvs janthomsen$ conda activate
(base) Jans-MacBook-Pro:my_rvs janthomsen$ radian
Traceback (most recent call last):
  File "/Users/janthomsen/opt/anaconda3/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/Users/janthomsen/opt/anaconda3/lib/python3.8/site-packages/radian/__init__.py", line 101, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/Users/janthomsen/opt/anaconda3/lib/python3.8/site-packages/radian/radianapp.py", line 94, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/Users/janthomsen/opt/anaconda3/lib/python3.8/site-packages/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: dlopen(/Users/janthomsen/opt/anaconda3/lib/R/lib/libR.dylib, 10): Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /Users/janthomsen/opt/anaconda3/lib/R/lib/libR.dylib
  Reason: image not found
(base) Jans-MacBook-Pro:my_rvs janthomsen$

**Comment by randy3k** [comment]
I think these is something fishy in your anaconda setup. Perhaps some libraries are updated or you have serval copies of conda which conflict each other.

**Comment by jatom-tech** [comment]
I think you could be right, i have anakonda3, conda and a miniconda. i dont know if you are only supposed to have one or?

what would you recommend?

conda list

   py38hf1fa96c_1  
brotlipy                  0.7.0           py38h9ed2024_1003  
bzip2                     1.0.8                h1de35cc_0  
c-ares                    1.17.1               h9ed2024_0  
ca-certificates           2021.5.30            h033912b_0    conda-forge
cachetools                4.2.2                    pypi_0    pypi
catalogue                 1.0.0                    pypi_0    pypi
certifi                   2021.5.30        py38h50d1736_0    conda-forge
cffi                      1.14.5           py38h2125817_0  
chardet                   4.0.0           py38hecd8cb5_1003  
click                     7.1.2              pyhd3eb1b0_0  
cloudpickle               1.6.0                      py_0  
clyent                    1.2.2                    py38_1  
colorama                  0.4.4              pyhd3eb1b0_0  
colorlover                0.3.0                    pypi_0    pypi
conda                     4.10.1           py38h50d1736_0    conda-forge
conda-build               3.21.4           py38hecd8cb5_0  
conda-content-trust       0.1.1              pyhd3eb1b0_0  
conda-env                 2.6.0                         1  
conda-package-handling    1.7.3            py38h9ed2024_1  
conda-repo-cli            1.0.4              pyhd3eb1b0_0  
conda-token               0.3.0              pyhd3eb1b0_0  
conda-verify              3.4.2                      py_1  
configobj                 5.0.6                    pypi_0    pypi
contextlib2               0.6.0.post1                py_0  
cryptography              3.4.7            py38h2fd3fbb_0  
cufflinks                 0.17.3                   pypi_0    pypi
curl                      7.71.1               hb0a8c7a_1  
cycler                    0.10.0                   py38_0  
cymem                     2.0.5                    pypi_0    pypi
cython                    0.29.23          py38h23ab428_0  
cytoolz                   0.11.0           py38haf1e3a3_0  
dask                      2021.4.0           pyhd3eb1b0_0  
dask-core                 2021.4.0           pyhd3eb1b0_0  
databricks-cli            0.14.3                   pypi_0    pypi
dbus                      1.13.18              h18a8e69_0  
decorator                 5.0.6              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713                   py_0  
distributed               2021.4.0         py38hecd8cb5_0  
docker                    5.0.0                    pypi_0    pypi
docutils                  0.17             py38hecd8cb5_1  
ecos                      2.0.7.post1      py38h2ec4a77_3    sebp
entrypoints               0.3                      py38_0  
envisage                  6.0.0                    pypi_0    pypi
et_xmlfile                1.0.1                   py_1001  
execnet                   1.8.1                    pypi_0    pypi
expat                     2.3.0                h23ab428_2  
fastcache                 1.1.0            py38h1de35cc_0  
filelock                  3.0.12             pyhd3eb1b0_1  
flake8                    3.9.0              pyhd3eb1b0_0  
flask                     1.1.2              pyhd3eb1b0_0  
flatbuffers               1.12                     pypi_0    pypi
formulaic                 0.2.3                    pypi_0    pypi
freetype                  2.10.4               ha233b18_0  
fsspec                    0.9.0              pyhd3eb1b0_0  
funcy                     1.16                     pypi_0    pypi
future                    0.18.2                   py38_1  
gast                      0.4.0                    pypi_0    pypi
geos                      3.8.0                hb1e8313_0    anaconda
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.21.0               h7535e17_0  
gevent                    21.1.2           py38h9ed2024_1  
gitdb                     4.0.7                    pypi_0    pypi
gitpython                 3.1.17                   pypi_0    pypi
glib                      2.68.1               hdf23fa2_0  
glob2                     0.7                pyhd3eb1b0_0  
gmp                       6.2.1                h23ab428_2  
gmpy2                     2.0.8            py38h6ef4df4_3  
google-auth               1.30.1                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
greenlet                  1.0.0            py38h23ab428_2  
grpcio                    1.34.1                   pypi_0    pypi
gsl                       2.4                  h1de35cc_4  
gunicorn                  20.1.0                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
hdf5                      1.10.4               hfa1e0ec_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.1                        py_0  
htmlmin                   0.1.12                   pypi_0    pypi
icu                       58.2                 h0a44026_3  
idna                      2.10               pyhd3eb1b0_0  
imagehash                 4.2.0                    pypi_0    pypi
imageio                   2.9.0              pyhd3eb1b0_0  
imagesize                 1.2.0              pyhd3eb1b0_0  
importlib-metadata        3.10.0           py38hecd8cb5_0  
importlib-resources       5.1.4                    pypi_0    pypi
importlib_metadata        3.10.0               hd3eb1b0_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intel-openmp              2021.2.0           hecd8cb5_564  
interface-meta            1.2.3                    pypi_0    pypi
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.22.0           py38h01d92e1_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
isort                     5.8.0              pyhd3eb1b0_0  
itsdangerous              1.1.0              pyhd3eb1b0_0  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4.1                      py_0  
jedi                      0.17.2           py38hecd8cb5_1  
jinja2                    2.11.3             pyhd3eb1b0_0  
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9b                   he5867d9_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py38_7  
jupyter-packaging         0.7.12             pyhd3eb1b0_0  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.7.1            py38hecd8cb5_0  
jupyter_server            1.4.1            py38hecd8cb5_0  
jupyterlab                3.0.16             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.4.0              pyhd3eb1b0_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
keras                     2.4.3                    pypi_0    pypi
keras-nightly             2.5.0.dev2021032900          pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   22.3.0           py38hecd8cb5_0  
kiwisolver                1.3.1            py38h23ab428_0  
krb5                      1.18.2               h75d18d8_0  
lazy-object-proxy         1.6.0            py38h9ed2024_0  
lcms2                     2.12                 hf1fd2bf_0  
libarchive                3.4.2                haa3ed63_0  
libcurl                   7.71.1               h8a08a2b_1  
libcxx                    11.1.0               habf9029_0    conda-forge
libedit                   3.1.20210216         h9ed2024_1  
libev                     4.33                 haf1e3a3_0  
libffi                    3.3                  hb1e8313_2  
libgcc                    4.8.5               hdbeacc1_10  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.16                 h1de35cc_0  
liblief                   0.10.1               h0a44026_0  
libllvm10                 10.0.1               h76017ad_5  
libllvm9                  9.0.1                h7475705_1    conda-forge
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.18               h1de35cc_0  
libspatialindex           1.9.3                h23ab428_0  
libssh2                   1.9.0                ha12b0ac_1  
libtiff                   4.2.0                h87d7836_0  
libuv                     1.40.0               haf1e3a3_0  
libwebp-base              1.2.0                h9ed2024_0  
libxgboost                1.3.3                h23ab428_0  
libxml2                   2.9.10               h7cdb67c_3  
libxslt                   1.1.34               h83b36ba_0  
lifelines                 0.26.0                   pypi_0    pypi
lineedit                  0.1.6                    pypi_0    pypi
llvm-openmp               10.0.0               h28b9765_0  
llvmlite                  0.36.0           py38he4411ff_4  
locket                    0.2.1            py38hecd8cb5_1  
lxml                      4.6.3            py38h26b266a_0  
lz4-c                     1.9.3                h23ab428_0  
lzo                       2.10                 haf1e3a3_2  
mako                      1.1.4                    pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                1.1.1            py38h1de35cc_1  
matplotlib                3.4.2                    pypi_0    pypi
matplotlib-base           3.3.4            py38h8b3ea08_0  
mayavi                    4.7.3                    pypi_0    pypi
mccabe                    0.6.1                    py38_1  
missingno                 0.4.2                    pypi_0    pypi
mistune                   0.8.4           py38h1de35cc_1001  
mkl                       2019.4                      233  
mkl-service               2.3.0            py38h9ed2024_0  
mkl_fft                   1.3.0            py38ha059aab_0  
mkl_random                1.1.1            py38h959d312_0  
mlflow                    1.17.0                   pypi_0    pypi
mlxtend                   0.18.0                   pypi_0    pypi
mock                      4.0.3              pyhd3eb1b0_0  
more-itertools            8.7.0              pyhd3eb1b0_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.2                h9066e36_1  
mpmath                    1.2.1            py38hecd8cb5_0  
msgpack-python            1.0.2            py38hf7b0b51_1  
multimethod               1.4                      pypi_0    pypi
multipledispatch          0.6.0                    py38_0  
murmurhash                1.0.5                    pypi_0    pypi
mypy_extensions           0.4.3                    py38_0  
navigator-updater         0.2.1                    py38_0  
nbclassic                 0.2.6              pyhd3eb1b0_0  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
networkx                  2.5                        py_0  
ninja                     1.10.2               hf7b0b51_1  
nltk                      3.6.1              pyhd3eb1b0_0  
nose                      1.3.7           pyhd3eb1b0_1006  
notebook                  6.3.0            py38hecd8cb5_0  
numba                     0.53.1           py38hb2f4e1b_0  
numexpr                   2.7.3            py38h16bde0e_0  
numpy                     1.19.5                   pypi_0    pypi
numpy-base                1.19.2           py38hcfb5961_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0  
openpyxl                  3.0.7              pyhd3eb1b0_0  
openssl                   1.1.1k               h0d85af4_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
osqp                      0.6.2.post0              pypi_0    pypi
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.2.4            py38h23ab428_0  
pandas-profiling          3.0.0                    pypi_0    pypi
pandoc                    2.12                 hecd8cb5_0  
pandocfilters             1.4.3            py38hecd8cb5_1  
parso                     0.7.0                      py_0  
partd                     1.2.0              pyhd3eb1b0_0  
path                      15.1.2           py38hecd8cb5_0  
path.py                   12.5.0                        0  
pathlib2                  2.3.5            py38hecd8cb5_2  
pathspec                  0.7.0                      py_0  
pathtools                 0.1.2                      py_1    conda-forge
patsy                     0.5.1                    py38_0  
pcre                      8.44                 hb1e8313_0  
pep8                      1.7.1                    py38_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
phik                      0.11.2                   pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.2.0            py38h5270095_0  
pip                       21.1.2                   pypi_0    pypi
pkginfo                   1.7.0            py38hecd8cb5_0  
plac                      1.1.3                    pypi_0    pypi
plotly                    4.14.3                   pypi_0    pypi
pluggy                    0.13.1           py38hecd8cb5_0  
ply                       3.11                     py38_0  
preshed                   3.0.5                    pypi_0    pypi
proj                      6.2.1                hfd5b9e3_0    anaconda
prometheus-flask-exporter 0.18.2                   pypi_0    pypi
prometheus_client         0.10.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
prompt_toolkit            3.0.17               hd3eb1b0_0  
protobuf                  3.17.1                   pypi_0    pypi
psutil                    5.8.0            py38h9ed2024_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py                        1.10.0             pyhd3eb1b0_0  
py-lief                   0.10.1           py38haf313ee_0  
py-xgboost                1.3.3            py38hecd8cb5_0  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.6.0              pyhd3eb1b0_0  
pycosat                   0.6.3            py38h1de35cc_1  
pycparser                 2.20                       py_2  
pycurl                    7.43.0.6         py38hddc9c9b_0  
pydantic                  1.8.2                    pypi_0    pypi
pydocstyle                6.0.0              pyhd3eb1b0_0  
pyerfa                    2.0.0            py38h9ed2024_0  
pyface                    7.3.0                    pypi_0    pypi
pyflakes                  2.2.0              pyhd3eb1b0_0  
pygments                  2.8.1              pyhd3eb1b0_0  
pyldavis                  3.2.2                    pypi_0    pypi
pylint                    2.7.4            py38hecd8cb5_1  
pyls-black                0.4.6                hd3eb1b0_0  
pyls-spyder               0.3.2              pyhd3eb1b0_0  
pynndescent               0.5.2                    pypi_0    pypi
pyod                      0.8.8                    pypi_0    pypi
pyodbc                    4.0.30           py38h0a44026_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyproj                    2.6.1.post1      py38h6d9c95c_1    anaconda
pyqt                      5.9.2            py38h655552a_2  
pyrsistent                0.17.3           py38haf1e3a3_0  
pyshp                     2.1.2                      py_0    anaconda
pysocks                   1.7.1                    py38_1  
pytables                  3.6.1            py38h4727e94_0  
pytest                    6.2.3            py38hecd8cb5_2  
pytest-forked             1.3.0                    pypi_0    pypi
pytest-xdist              2.2.1                    pypi_0    pypi
python                    3.8.8                h88f2d9e_5  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-editor             1.0.4                    pypi_0    pypi
python-graphviz           0.16                     pypi_0    pypi
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.36.2             pyhd3eb1b0_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python.app                3                py38h9ed2024_0  
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.4.0           cpu_py38hf9bb1df_0  
pytz                      2021.1             pyhd3eb1b0_0  
pywavelets                1.1.1            py38haf1e3a3_2  
pyyaml                    5.4.1            py38h9ed2024_1  
pyzmq                     20.0.0           py38h23ab428_1  
qdarkstyle                2.8.1                      py_0  
qdldl                     0.1.5.post0              pypi_0    pypi
qt                        5.9.7                h468cd18_1  
qtawesome                 1.0.2              pyhd3eb1b0_0  
qtconsole                 5.0.3              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
querystring-parser        1.2.4                    pypi_0    pypi
r                         3.3.1                  r3.3.1_0    r
r-assertthat              0.1                    r3.3.1_4    r
r-base                    3.3.1                         0    r
r-base64enc               0.1_3                  r3.3.1_0    r
r-bh                      1.60.0_2               r3.3.1_0    r
r-bitops                  1.0_6                  r3.3.1_2    r
r-boot                    1.3_18                 r3.3.1_0    r
r-car                     2.1_2                  r3.3.1_0    r
r-caret                   6.0_70                 r3.3.1_0    r
r-catools                 1.17.1                 r3.3.1_2    r
r-chron                   2.3_47                 r3.3.1_0    r
r-class                   7.3_14                 r3.3.1_0    r
r-cluster                 2.0.4                  r3.3.1_0    r
r-codetools               0.2_14                 r3.3.1_0    r
r-colorspace              1.2_6                  r3.3.1_0    r
r-crayon                  1.3.1                  r3.3.1_0    r
r-curl                    0.9.7                  r3.3.1_0    r
r-data.table              1.9.6                  r3.3.1_0    r
r-dbi                     0.4_1                  r3.3.1_0    r
r-dichromat               2.0_0                  r3.3.1_2    r
r-digest                  0.6.9                  r3.3.1_0    r
r-dplyr                   0.4.3                  r3.3.1_0    r
r-essentials              1.4.3                  r3.3.1_0    r
r-evaluate                0.9                    r3.3.1_0    r
r-foreach                 1.4.3                  r3.3.1_0    r
r-foreign                 0.8_66                 r3.3.1_0    r
r-formatr                 1.4                    r3.3.1_0    r
r-ggplot2                 2.1.0                  r3.3.1_0    r
r-gistr                   0.3.6                  r3.3.1_0    r
r-glmnet                  2.0_5                  r3.3.1_0    r
r-gtable                  0.2.0                  r3.3.1_0    r
r-hexbin                  1.27.1                 r3.3.1_0    r
r-highr                   0.6                    r3.3.1_0    r
r-htmltools               0.3.5                  r3.3.1_0    r
r-htmlwidgets             0.6                    r3.3.1_0    r
r-httpuv                  1.3.3                  r3.3.1_0    r
r-httr                    1.2.0                  r3.3.1_0    r
r-irdisplay               0.4.3                  r3.3.1_2    r
r-irkernel                0.7                    r3.3.1_2    r
r-iterators               1.0.8                  r3.3.1_0    r
r-jsonlite                0.9.22                 r3.3.1_0    r
r-kernsmooth              2.23_15                r3.3.1_0    r
r-knitr                   1.13                   r3.3.1_0    r
r-labeling                0.3                    r3.3.1_2    r
r-lattice                 0.20_33                r3.3.1_0    r
r-lazyeval                0.2.0                  r3.3.1_0    r
r-lme4                    1.1_12                 r3.3.1_0    r
r-magrittr                1.5                    r3.3.1_2    r
r-maps                    3.1.0                  r3.3.1_0    r
r-markdown                0.7.7                  r3.3.1_2    r
r-mass                    7.3_45                 r3.3.1_0    r
r-matrix                  1.2_6                  r3.3.1_0    r
r-matrixmodels            0.4_1                  r3.3.1_0    r
r-memoise                 1.0.0                  r3.3.1_0    r
r-mgcv                    1.8_12                 r3.3.1_0    r
r-mime                    0.4                    r3.3.1_0    r
r-minqa                   1.2.4                  r3.3.1_2    r
r-munsell                 0.4.3                  r3.3.1_0    r
r-nlme                    3.1_128                r3.3.1_0    r
r-nloptr                  1.0.4                  r3.3.1_2    r
r-nnet                    7.3_12                 r3.3.1_0    r
r-openssl                 0.9.4                  r3.3.1_0    r
r-pbdzmq                  0.2_3                  r3.3.1_0    r
r-pbkrtest                0.4_6                  r3.3.1_0    r
r-plyr                    1.8.4                  r3.3.1_0    r
r-pryr                    0.1.2                  r3.3.1_0    r
r-quantmod                0.4_5                  r3.3.1_2    r
r-quantreg                5.26                   r3.3.1_0    r
r-r6                      2.1.2                  r3.3.1_0    r
r-randomforest            4.6_12                 r3.3.1_0    r
r-rbokeh                  0.4.2                  r3.3.1_0    r
r-rcolorbrewer            1.1_2                  r3.3.1_3    r
r-rcpp                    0.12.5                 r3.3.1_0    r
r-rcppeigen               0.3.2.8.1              r3.3.1_0    r
r-recommended             3.3.1                  r3.3.1_0    r
r-repr                    0.7                    r3.3.1_0    r
r-reshape2                1.4.1                  r3.3.1_2    r
r-rmarkdown               0.9.6                  r3.3.1_0    r
r-rpart                   4.1_10                 r3.3.1_0    r
r-scales                  0.4.0                  r3.3.1_0    r
r-shiny                   0.13.2                 r3.3.1_0    r
r-sparsem                 1.7                    r3.3.1_0    r
r-spatial                 7.3_11                 r3.3.1_0    r
r-stringi                 1.1.1                  r3.3.1_0    r
r-stringr                 1.0.0                  r3.3.1_0    r
r-survival                2.39_4                 r3.3.1_0    r
r-tibble                  1.0                    r3.3.1_0    r
r-tidyr                   0.5.1                  r3.3.1_0    r
r-ttr                     0.23_1                 r3.3.1_0    r
r-uuid                    0.1_2                  r3.3.1_0    r
r-xtable                  1.8_2                  r3.3.1_0    r
r-xts                     0.9_7                  r3.3.1_2    r
r-yaml                    2.1.13                 r3.3.1_2    r
r-zoo                     1.7_13                 r3.3.1_0    r
radian                    0.5.10                   pypi_0    pypi
rchitect                  0.3.30                   pypi_0    pypi
readline                  8.1                  h9ed2024_0  
regex                     2021.4.4         py38h9ed2024_0  
requests                  2.25.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                    pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
ripgrep                   12.1.1                        0  
rope                      0.18.0                     py_0  
rsa                       4.7.2                    pypi_0    pypi
rtree                     0.9.7            py38hecd8cb5_1  
ruamel_yaml               0.15.100         py38h9ed2024_0  
scikit-image              0.18.1           py38hb2f4e1b_0  
scikit-learn              0.23.2                   pypi_0    pypi
scikit-plot               0.3.7                    pypi_0    pypi
scikit-survival           0.15.0.post0     py38ha57c2b5_0    sebp
scipy                     1.5.4                    pypi_0    pypi
seaborn                   0.11.1             pyhd3eb1b0_0  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                52.0.0           py38hecd8cb5_0  
shap                      0.39.0           py38h1f261ad_0    conda-forge
simplegeneric             0.8.1                    py38_2  
singledispatch            3.6.1           pyhd3eb1b0_1001  
sip                       4.19.8           py38h0a44026_0  
siuba                     0.0.24                   pypi_0    pypi
six                       1.15.0           py38hecd8cb5_0  
sklearn                   0.0                      pypi_0    pypi
slicer                    0.0.7              pyhd8ed1ab_0    conda-forge
smart-open                5.1.0                    pypi_0    pypi
smmap                     4.0.0                    pypi_0    pypi
snappy                    1.1.8                h4a8c4bd_3    conda-forge
sniffio                   1.2.0            py38hecd8cb5_1  
snowballstemmer           2.1.0              pyhd3eb1b0_0  
sortedcollections         2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.3.0              pyhd3eb1b0_0  
soupsieve                 2.2.1              pyhd3eb1b0_0  
spacy                     2.3.5                    pypi_0    pypi
sphinx                    4.0.1              pyhd3eb1b0_0  
sphinxcontrib             1.0                      py38_1  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0  
sphinxcontrib-websupport  1.2.4                      py_0  
spyder                    4.2.5            py38hecd8cb5_0  
spyder-kernels            1.10.2           py38hecd8cb5_0  
sqlalchemy                1.4.7            py38h9ed2024_0  
sqlite                    3.35.4               hce871da_0  
sqlparse                  0.4.1                    pypi_0    pypi
srsly                     1.0.5                    pypi_0    pypi
statsmodels               0.12.2           py38h9ed2024_0  
sympy                     1.8              py38hecd8cb5_0  
tabulate                  0.8.9                    pypi_0    pypi
tangled-up-in-unicode     0.1.0                    pypi_0    pypi
tbb                       2020.3               h879752b_0  
tblib                     1.7.0                      py_0  
tensorboard               2.5.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.4            py38hecd8cb5_0  
testpath                  0.4.4              pyhd3eb1b0_0  
textblob                  0.15.3                   pypi_0    pypi
textdistance              4.2.1              pyhd3eb1b0_0  
tflearn                   0.5.0                    pypi_0    pypi
thinc                     7.4.5                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2020.10.1        py38h0cf3a3e_2  
tk                        8.6.10               hb0a8c7a_0  
toml                      0.10.2             pyhd3eb1b0_0  
toolz                     0.11.1             pyhd3eb1b0_0  
tornado                   6.1              py38h9ed2024_0  
tqdm                      4.59.0             pyhd3eb1b0_1  
traitlets                 5.0.5              pyhd3eb1b0_0  
traits                    6.2.0                    pypi_0    pypi
traitsui                  7.2.1                    pypi_0    pypi
typed-ast                 1.4.2            py38h9ed2024_1  
typing_extensions         3.7.4.3            pyha847dfd_0  
ujson                     4.0.2            py38h23ab428_0  
umap-learn                0.5.1                    pypi_0    pypi
unicodecsv                0.14.1                   py38_0  
unixodbc                  2.3.9                haf1e3a3_0  
urllib3                   1.26.4             pyhd3eb1b0_0  
visions                   0.7.1                    pypi_0    pypi
voila                     0.2.10                   pypi_0    pypi
vtk                       9.0.1                    pypi_0    pypi
wasabi                    0.8.2                    pypi_0    pypi
watchdog                  1.0.2            py38h9ed2024_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
websocket-client          1.0.1                    pypi_0    pypi
werkzeug                  1.0.1              pyhd3eb1b0_0  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    py38_0  
wordcloud                 1.8.1                    pypi_0    pypi
wrapt                     1.12.1           py38haf1e3a3_1  
wurlitzer                 2.1.0            py38hecd8cb5_0  
xgboost                   1.4.2                    pypi_0    pypi
xlrd                      2.0.1              pyhd3eb1b0_0  
xlsxwriter                1.3.8              pyhd3eb1b0_0  
xlwings                   0.23.0           py38hecd8cb5_0  
xlwt                      1.3.0                    py38_0  
xmltodict                 0.12.0                     py_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
yapf                      0.31.0             pyhd3eb1b0_0  
yellowbrick               1.3.post1                pypi_0    pypi
zeromq                    4.3.4                h23ab428_0  
zict                      2.0.0              pyhd3eb1b0_0  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h1de35cc_3  
zope                      1.0                      py38_1  
zope.event                4.5.0                    py38_0  
zope.interface            5.3.0            py38h9ed2024_0  
zstd                      1.4.5                h41d2c2f_0  
(base) Jans-MacBook-Pro:~ janthomsen$
