### ISSUE TITLE
successfully installed but failed to launch radian 

### ISSUE THREAD

**Issue by fdq09eca** [randy3k/radian#290]
I installed radian by `pip3 install radian` but it does not run as expected and I got the following error.

```
chrislam@ChrisLams-MBP GendooLab % radian
Traceback (most recent call last):
  File "/opt/homebrew/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/radian/__init__.py", line 11, in main
    from rchitect.utils import Rhome, rversion
  File "/opt/homebrew/lib/python3.9/site-packages/rchitect/__init__.py", line 1, in <module>
    from .setup import init, loop
  File "/opt/homebrew/lib/python3.9/site-packages/rchitect/setup.py", line 6, in <module>
    from rchitect._cffi import ffi, lib
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        /opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture
        /opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture
```
I am on a M1 Mac BigSur

**Comment by randy3k** [comment]
Try reinstalling cffi, it seems a wheel with wrong arch was installed.

**Comment by fdq09eca** [comment]
> Try reinstalling cffi, it seems a wheel with wrong arch was installed.

sorry, I am very new. would you please tell me how to reinstall `cffi`?

more info, if any worth.
```
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z (1 mo ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0
```

**Comment by randy3k** [comment]
How about forcing no binary?

```

pip install --no-binary :all: radian

```

**Comment by fdq09eca** [comment]
```
chrislam@ChrisLams-MBP ~ % pip3 uninstall radian
Found existing installation: radian 0.5.11
Uninstalling radian-0.5.11:
  Would remove:
    /opt/homebrew/bin/radian
    /opt/homebrew/lib/python3.9/site-packages/radian-0.5.11.dist-info/*
    /opt/homebrew/lib/python3.9/site-packages/radian/*
Proceed (y/n)? y
  Successfully uninstalled radian-0.5.11
chrislam@ChrisLams-MBP ~ % pip install --no-binary :all: radian
zsh: command not found: pip
chrislam@ChrisLams-MBP ~ % pip3 install --no-binary :all: radian
Collecting radian
  Using cached radian-0.5.11.tar.gz (48 kB)
Requirement already satisfied: rchitect<0.4.0,>=0.3.30 in /opt/homebrew/lib/python3.9/site-packages (from radian) (0.3.32)
Requirement already satisfied: lineedit<0.2.0,>=0.1.5 in /opt/homebrew/lib/python3.9/site-packages (from radian) (0.1.6)
Requirement already satisfied: six>=1.9.0 in ./Library/Python/3.9/lib/python/site-packages (from radian) (1.15.0)
Requirement already satisfied: pygments>=2.5.0 in ./Library/Python/3.9/lib/python/site-packages (from radian) (2.8.0)
Requirement already satisfied: wcwidth in ./Library/Python/3.9/lib/python/site-packages (from lineedit<0.2.0,>=0.1.5->radian) (0.2.5)
Requirement already satisfied: cffi>=1.10.0 in /opt/homebrew/lib/python3.9/site-packages (from rchitect<0.4.0,>=0.3.30->radian) (1.14.5)
Requirement already satisfied: pycparser in /opt/homebrew/lib/python3.9/site-packages (from cffi>=1.10.0->rchitect<0.4.0,>=0.3.30->radian) (2.20)
Skipping wheel build for radian, due to binaries being disabled for it.
Installing collected packages: radian
    Running setup.py install for radian ... done
Successfully installed radian-0.5.11
WARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.
You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
chrislam@ChrisLams-MBP ~ % radian
Traceback (most recent call last):
  File "/opt/homebrew/bin/radian", line 33, in <module>
    sys.exit(load_entry_point('radian==0.5.11', 'console_scripts', 'radian')())
  File "/opt/homebrew/lib/python3.9/site-packages/radian/__init__.py", line 11, in main
    from rchitect.utils import Rhome, rversion
  File "/opt/homebrew/lib/python3.9/site-packages/rchitect/__init__.py", line 1, in <module>
    from .setup import init, loop
  File "/opt/homebrew/lib/python3.9/site-packages/rchitect/setup.py", line 6, in <module>
    from rchitect._cffi import ffi, lib
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture
	/opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture
chrislam@ChrisLams-MBP ~ % 
```

same error?

**Comment by randy3k** [comment]
Please remove cffi first.

**Comment by fdq09eca** [comment]
@randy3k Bingo!

```
chrislam@ChrisLams-MBP ~ % pip3 uninstall radian
Found existing installation: radian 0.5.11
Uninstalling radian-0.5.11:
  Would remove:
    /opt/homebrew/bin/radian
    /opt/homebrew/lib/python3.9/site-packages/radian-0.5.11-py3.9.egg-info
    /opt/homebrew/lib/python3.9/site-packages/radian/*
Proceed (y/n)? y
  Successfully uninstalled radian-0.5.11
chrislam@ChrisLams-MBP ~ % pip3 uninstall cffi
Found existing installation: cffi 1.14.5
Uninstalling cffi-1.14.5:
  Would remove:
    /opt/homebrew/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
    /opt/homebrew/lib/python3.9/site-packages/cffi-1.14.5.dist-info/*
    /opt/homebrew/lib/python3.9/site-packages/cffi/*
Proceed (y/n)? y
  Successfully uninstalled cffi-1.14.5
chrislam@ChrisLams-MBP ~ % pip3 install --no-binary :all: radian
Collecting radian
  Using cached radian-0.5.11.tar.gz (48 kB)
Requirement already satisfied: rchitect<0.4.0,>=0.3.30 in /opt/homebrew/lib/python3.9/site-packages (from radian) (0.3.32)
Requirement already satisfied: lineedit<0.2.0,>=0.1.5 in /opt/homebrew/lib/python3.9/site-packages (from radian) (0.1.6)
Requirement already satisfied: six>=1.9.0 in ./Library/Python/3.9/lib/python/site-packages (from radian) (1.15.0)
Requirement already satisfied: pygments>=2.5.0 in ./Library/Python/3.9/lib/python/site-packages (from radian) (2.8.0)
Requirement already satisfied: wcwidth in ./Library/Python/3.9/lib/python/site-packages (from lineedit<0.2.0,>=0.1.5->radian) (0.2.5)
Collecting cffi>=1.10.0
  Using cached cffi-1.14.5.tar.gz (475 kB)
Requirement already satisfied: pycparser in /opt/homebrew/lib/python3.9/site-packages (from cffi>=1.10.0->rchitect<0.4.0,>=0.3.30->radian) (2.20)
Skipping wheel build for radian, due to binaries being disabled for it.
Skipping wheel build for cffi, due to binaries being disabled for it.
Installing collected packages: cffi, radian
    Running setup.py install for cffi ... done
    Running setup.py install for radian ... done
Successfully installed cffi-1.14.5 radian-0.5.11
WARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.
You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
chrislam@ChrisLams-MBP ~ % radian
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Platform: aarch64-apple-darwin20 (64-bit)

r$>  
```
