### ISSUE TITLE
signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by renkun-ken** [randy3k/radian#294]
Running the following [torch example](https://torch.mlverse.org/start/guess_the_correlation/) in latest radian will crash:

```r
# install.packages("torch")
# install.packages("torchvision")
# remotes::install_github("mlverse/torchdatasets")

library(torch)
library(torchvision)
library(torchdatasets)

torch_tensor(1)

train_indices <- 1:10000
val_indices <- 10001:15000
test_indices <- 15001:20000

add_channel_dim <- function(img) img$unsqueeze(1)
crop_axes <- function(img) transform_crop(img, top = 0, left = 21, height = 131, width = 130)

root <- file.path(tempdir(), "correlation")

train_ds <- guess_the_correlation_dataset(
  # where to unpack
  root = root,
  # additional preprocessing
  transform = function(img) crop_axes(img) |> add_channel_dim(),
  # don't take all data, but just the indices we pass in
  indexes = train_indices,
  download = TRUE
)

valid_ds <- guess_the_correlation_dataset(
  root = root,
  transform = function(img) crop_axes(img) |> add_channel_dim(),
  indexes = val_indices,
  download = FALSE
)

test_ds <- guess_the_correlation_dataset(
  root = root,
  transform = function(img) crop_axes(img) |> add_channel_dim(),
  indexes = test_indices,
  download = FALSE
)

length(train_ds)
length(valid_ds)
length(test_ds)

train_ds[1]

train_dl <- dataloader(train_ds, batch_size = 64, shuffle = TRUE)
length(train_dl)

batch <- dataloader_make_iter(train_dl) |> dataloader_next()

dim(batch$x)
dim(batch$y)

par(mfrow = c(8, 8), mar = rep(0, 4))
```

An infinite loop of printing `<class 'ValueError'> signal only works in main thread of the main interpreter ` in the prompt will appear
and enter any command will end up in the following error:

```
> <class 'ValueError'> signal only works in main thread of the main interpreter                                                                                                            
> <class 'ValueError'> signal only works in main thread of the main interpreter                                                                                                            
> <class 'ValueError'> signal only works in main thread of the main interpreter                                                                                                            
> <class 'ValueError'> signal only works in main thread of the main interpreter                                                                                                            
<class 'ValueError'> signal only works in main thread of the main interpreter
unexpected error was caught.
please report to https://github.com/randy3k/radian for such error.
Event loop is already running
unexpected error was caught.
please report to https://github.com/randy3k/radian for such error.
list.remove(x): x not in list
Traceback (most recent call last):
  File "/home/renkun/.local/lib/python3.9/site-packages/radian/console.py", line 96, in read_console
    text = session.prompt(add_history=add_history)
  File "/home/renkun/.local/lib/python3.9/site-packages/lineedit/prompt.py", line 231, in prompt
    result = super(ModalPromptSession, self).prompt(**kwargs)
  File "/home/renkun/.local/lib/python3.9/site-packages/lineedit/deps/prompt_toolkit/shortcuts/prompt.py", line 797, in prompt
    return run_sync()
  File "/home/renkun/.local/lib/python3.9/site-packages/lineedit/deps/prompt_toolkit/shortcuts/prompt.py", line 786, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "/home/renkun/.local/lib/python3.9/site-packages/lineedit/deps/prompt_toolkit/application/application.py", line 736, in run
    return run()
  File "/home/renkun/.local/lib/python3.9/site-packages/lineedit/deps/prompt_toolkit/application/application.py", line 709, in run
    run_until_complete(f, inputhook=inputhook)
  File "/home/renkun/.local/lib/python3.9/site-packages/lineedit/deps/prompt_toolkit/eventloop/defaults.py", line 126, in run_until_complete
    return get_event_loop().run_until_complete(future, inputhook=inputhook)
  File "/home/renkun/.local/lib/python3.9/site-packages/lineedit/deps/prompt_toolkit/eventloop/posix.py", line 58, in run_until_complete
    raise Exception('Event loop is already running')
Exception: Event loop is already running
```

**Comment by randy3k** [comment]
It runs fine on my computer. Were you trying to send a signal to the process?

**Comment by randy3k** [comment]
Prehapa Linux issue, let me try it on a linux.
