### ISSUE TITLE
radian not starting in Termux after some updates

### ISSUE THREAD

**Issue by rrodrigueznt** [randy3k/radian#300]
Hi! I was really enjoying Radian and learning a lot about working out issues while compiling R packages in Termux when some change/update ruins the party! Not able to figure out what.

Here what I get at starting time:

```
~ $ radian
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/radian/__init__.py", line 11, in main
    from rchitect.utils import Rhome, rversion
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/rchitect/__init__.py", line 1, in <module>
    from .setup import init, loop
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/rchitect/setup.py", line 6, in <module>
    from rchitect._cffi import ffi, lib
ImportError: dlopen failed: cannot locate symbol "ffi_type_sint64" referenced by "/data/data/com.termux/files/usr/lib/python3.9/site-packages/_cffi_backend.cpython-39.so"...
~ $
```
Python version:
```
~ $ python --version
Python 3.9.6
~ $
```
I've googled around looking for clues to no avail.

Please, could you help me with this problem? Thanks!

**Comment by randy3k** [comment]
It seems like an issue of cffi. How about installing it from source?
```
pip install --no-binary :all: cffi
```

**Comment by rrodrigueznt** [comment]
Hi! Thanks for the follow up. Installing it from source didn't help The issue seams related with cffi 1.14.6. Radian starts correctly with cffi 1.14.5. Please, read below:

```
.../usr/bin $ nm /data/data/com.termux/files/usr/lib/libffi.so -D | grep ffi_type_sint64
0000000000014190 R ffi_type_sint64@@LIBFFI_BASE_8.0
.../usr/bin $ nm -D /data/data/com.termux/files/usr/lib/python3.9/site-packages/_cffi_backend.cpython-39.so | grep ffi_type_sint64
                 U ffi_type_sint64@LIBFFI_BASE_7.0
.../usr/bin $
```

I uninstalled cffi 1.14.6 and install 1.14.5 as per:

```
.../usr/bin $ pip uninstall cffi==1.14.6
Found existing installation: cffi 1.14.6
Uninstalling cffi-1.14.6:
  Would remove:
    /data/data/com.termux/files/usr/lib/python3.9/site-packages/_cffi_backend.cpython-39.so
    /data/data/com.termux/files/usr/lib/python3.9/site-packages/cffi-1.14.6.dist-info/*
    /data/data/com.termux/files/usr/lib/python3.9/site-packages/cffi/*
Proceed (Y/n)? Y
  Successfully uninstalled cffi-1.14.6
.../usr/bin $ pip install cffi==1.14.5
Collecting cffi==1.14.5
  Using cached cffi-1.14.5-cp39-cp39-linux_aarch64.whl
Requirement already satisfied: pycparser in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from cffi==1.14.5) (2.20)
Installing collected packages: cffi
Successfully installed cffi-1.14.5
.../usr/bin $
```

Now, I get:

```
.../usr/bin $ nm /data/data/com.termux/files/usr/lib/libffi.so -D | grep ffi_type_sint64
0000000000014190 R ffi_type_sint64@@LIBFFI_BASE_8.0
.../usr/bin $ nm -D /data/data/com.termux/files/usr/lib/python3.9/site-packages/_cffi_backend.cpython-39.so | grep ffi_type_sint64
                 U ffi_type_sint64@LIBFFI_BASE_8.0
.../usr/bin $
```

And radian starts correctly. Please, does it make sense to you that cffi 1.14.6 _cffi_backend.cpython-39.so calls  **ffi_type_sint64@LIBFFI_BASE_7.0** and cffi 1.14.5 _cffi_backend.cpython-39.so calls **ffi_type_sint64@LIBFFI_BASE_8.0**?

Please, consider that I'm completely new in this arena! I can easily misunderstand what I'm getting here! Could I be of any further help to work out this issue? Thanks for your work! Termux is an extremely valuable piece of sofware!

**Comment by randy3k** [comment]
I'm glad that you found a solution. I have no idea why it was linking with a different version of libffi. Though I suppose if you install cffi from source, it should be able to pick up the correct version of the library.

**Comment by rrodrigueznt** [comment]
Nope, installing from the source didn't help.

As far as I've been learning, I can use nm to list all symbols defined or required by a dynamic library. Thus, it seems that _cffi_backend.cpython-39.so in cffi 1.14.6 is looking for ffi_type_sint64@LIBFFI_BASE_7.0, but libffi.so includes ffi_type_sint64@LIBFFI_BASE_8.0.

Only when I install cffi 1.14.5, _cffi_backend.cpython-39.so looks for ffi_type_sint64@LIBFFI_BASE_8.0.

So, does it make sense that _cffi_backend.cpython-39.so at cffi 1.14.5 requires ffi_type_sint64@LIBFFI_BASE_8.0 and at cffi 1.14.6 requires ffi_type_sint64@LIBFFI_BASE_7.0?

Thanks!
