### ISSUE TITLE
Documentation amendment suggestion

### ISSUE THREAD

**Issue by francisbarton** [randy3k/radian#309]
I am an RStudio user wanting to experiment with using radian (probably within Code).

I installed miniconda3 (python 3.9) on Windows 10, and then installed radian without error. Then when I typed `radian` at the anaconda prompt, I got:

> Traceback (most recent call last):
  File "C:\Users\Francis\Programs\miniconda3\Scripts\radian-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Francis\Programs\miniconda3\lib\site-packages\radian\__init__.py", line 51, in main
    r_home = Rhome()
  File "C:\Users\Francis\Programs\miniconda3\lib\site-packages\rchitect\utils.py", line 85, in Rhome
    raise RuntimeError("Cannot determine R HOME.")
RuntimeError: Cannot determine R HOME.

I then tried following the instructions to set R HOME in your README, like this:
> env R_HOME=C:\Users\Francis\Programs\R\R-4.1.1 radian

but this gave the error:
> 'env' is not recognized as an internal or external command,
operable program or batch file.

However when I did
>  set R_HOME=C:\Users\Francis\Programs\R\R-4.1.1

I got no error and was able to then start radian.

I think it might be helpful to others to include the `set` option as well as the `env` option in the README.

**Comment by Kevinobote** [comment]
I also got the same issue:
I had installed R
I proceeded to add the R installation to the path to the system environment variables, this allowed me to run radian without issues.

![Radian](https://github.com/user-attachments/assets/984b7574-fd72-4925-b402-5df566e60981)
