### ISSUE TITLE
Radian can not be opened.

### ISSUE THREAD

**Issue by seedvestige** [randy3k/radian#336]
I have installed radian in Centos7, but when I opened radian, it showed me the error as below.

Traceback (most recent call last):
  File "/home/zhengjieou/software/Anaconda/anaconda3/envs/py39/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/home/zhengjieou/software/Anaconda/anaconda3/envs/py39/lib/python3.9/site-packages/radian/__init__.py", line 51, in main
    r_home = Rhome()
  File "/home/zhengjieou/software/Anaconda/anaconda3/envs/py39/lib/python3.9/site-packages/rchitect/utils.py", line 87, in Rhome
    verify_Rhome(rhome)
  File "/home/zhengjieou/software/Anaconda/anaconda3/envs/py39/lib/python3.9/site-packages/rchitect/utils.py", line 56, in verify_Rhome
    raise RuntimeError("R share library ({}) does not exist.".format(path))
RuntimeError: R share library (/home/zhengjieou/software/R/lib64/R/lib/libR.so) does not exist.

I don't know how to deal with this problem. 
Thank you so much for your help!

**Comment by czg-sci-42ver** [comment]
I think your R installation is not proper by `R share library (/home/zhengjieou/software/R/lib64/R/lib/libR.so) does not exist.` which is listed in the `README.md`

- I use ubuntu and install by [the official help](https://cran.r-project.org/bin/linux/ubuntu/) and 
```bash
sudo apt-get install r-base-dev
```
  by [this](https://cran.r-project.org/bin/linux/ubuntu/fullREADME.html)
- you can try [this](https://linuxize.com/post/how-to-install-r-on-centos-7/) similarly or [instructions on the Rstudio](https://docs.rstudio.com/resources/install-r/)(whose installation in ubuntu is a little different from my practice，but Rstudio blog is trustworthy :smile:)

**Comment by seedvestige** [comment]
Thank you so much! I have solved this problem by reinstalling R.
Add "./configure --enable-R-shlib --with-readline=yes --with-libpng=yes --with-blas  -prefix=usr/home/xxx/" when installing.
