### ISSUE TITLE
Can't use radian on system terminal

### ISSUE THREAD

**Issue by chenyiwrites** [randy3k/radian#340]
Hi, I used to write R in RStudio and am moving to VS Code (Windows 10). My radian isn't working on VS Code nor on system terminal.

On the system terminal, `RuntimeError: Cannot determine R HOME` would be raised whenever I started a new session:
```
Traceback (most recent call last):
  File "C:\Users\cheny\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cheny\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\cheny\anaconda3\Scripts\radian.exe\__main__.py", line 7, in <module>
  File "C:\Users\cheny\anaconda3\lib\site-packages\radian\__init__.py", line 51, in main
    r_home = Rhome()
  File "C:\Users\cheny\anaconda3\lib\site-packages\rchitect\utils.py", line 85, in Rhome
    raise RuntimeError("Cannot determine R HOME.")
RuntimeError: Cannot determine R HOME.
```
Within the same session, I could fix it by `set R_HOME=C:\Program Files\R\R-4.1.2`:
<img width="542" alt="radian" src="https://user-images.githubusercontent.com/34919390/154846838-de6e4f4a-d7aa-4c96-a7dd-cc550523eb1b.png">
However, every time I started a new session on the sytsem terminal, I had to set R_HOME so that I could use radian. Does anyone know how to settle it once and for all? I have only one version of R installed. Thanks a lot!

**Comment by randy3k** [comment]
You could put the variable as an environmental variable on Windows.
See for example https://www.computerhope.com/issues/ch000549.htm.
