### ISSUE TITLE
TypeError: ModelHistory.load() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by MiguelRodo** [randy3k/radian#345]
Hi 

Thank you for creating a great terminal. 

I have been using it on Windows successfully, but am having the following problem on a CentOS 7 server. Here is the final line from the error message after installing `radian` and running `radian`:

```python
TypeError: ModelHistory.load() takes 1 positional argument but 2 were given
``` 

Here is the entire error message:

```python
Traceback (most recent call last):
  File "/home/rdxmig002/.conda/envs/StandardEnv/bin/radian", line 10, in <module>
    sys.exit(main())
  File "/home/rdxmig002/.conda/envs/StandardEnv/lib/python3.10/site-packages/radian/app.py", line 108, in main
    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)
  File "/home/rdxmig002/.conda/envs/StandardEnv/lib/python3.10/site-packages/radian/app.py", line 215, in run
    self.session = create_radian_prompt_session(options, settings)
  File "/home/rdxmig002/.conda/envs/StandardEnv/lib/python3.10/site-packages/radian/prompt_session.py", line 152, in create_radian_prompt_session
    session = RadianPromptSession(
  File "/home/rdxmig002/.conda/envs/StandardEnv/lib/python3.10/site-packages/radian/lineedit/prompt.py", line 72, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/exp_soft/anaconda3/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 456, in __init__
    self.default_buffer = self._create_default_buffer()
  File "/home/rdxmig002/.conda/envs/StandardEnv/lib/python3.10/site-packages/radian/lineedit/prompt.py", line 163, in _create_default_buffer
    return ModalBuffer(
  File "/home/rdxmig002/.conda/envs/StandardEnv/lib/python3.10/site-packages/radian/lineedit/buffer.py", line 185, in __init__
    super().__init__(*args, **kwargs)
  File "/home/rdxmig002/.conda/envs/StandardEnv/lib/python3.10/site-packages/radian/lineedit/buffer.py", line 22, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/exp_soft/anaconda3/lib/python3.7/site-packages/prompt_toolkit/buffer.py", line 316, in __init__
    self.history.load(new_history_item)
TypeError: ModelHistory.load() takes 1 positional argument but 2 were given
```

The command `radian` seems to be on the path then. I get the same error message after the `conda` and `pip` installation routes. I unfortunately don't know where to start debugging such issues more than that.

**Comment by randy3k** [comment]
It seems that you are using an old version of prompt toolkit. Not sure why prompt toolkit was not upgraded.
