### ISSUE TITLE
RuntimeError: R and python architectures do not match

### ISSUE THREAD

**Issue by Mark-S2004** [randy3k/radian#357]
OS: Windows 10
Python version: 3.8.3
R path: C:\Program Files\R\R-4.2.0\bin\x64

When I run radian in my terminal, the output is:
`Traceback (most recent call last):
  File "C:\Users\miker\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\miker\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\miker\AppData\Local\Programs\Python\Python38-32\Scripts\radian.exe\__main__.py", line 7, in <module>
  File "C:\Users\miker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\radian\app.py", line 52, in main
    r_home = Rhome()
  File "C:\Users\miker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\rchitect\utils.py", line 87, in Rhome
    verify_Rhome(rhome)
  File "C:\Users\miker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\rchitect\utils.py", line 55, in verify_Rhome
    raise RuntimeError("R and python architectures do not match.")
RuntimeError: R and python architectures do not match.`

**Comment by randy3k** [comment]
As suggested, you need to make sure both python and R are built from the same architecture, ie both Intel or both M1.

**Comment by Mark-S2004** [comment]
Thanks for the clarification &#128522;

**Comment by 00-star** [comment]
How to build them to the same architecture?
