### ISSUE TITLE
libreadline.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by AfterDream** [randy3k/radian#370]
I install radian with conda (version = 4.13), but fail to open it, and the error information is:
Traceback (most recent call last):
  File "/home/shpc_100539/miniconda3/bin/radian", line 10, in <module>
    sys.exit(main())
  File "/home/shpc_100539/miniconda3/lib/python3.9/site-packages/radian/app.py", line 108, in main
    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)
  File "/home/shpc_100539/miniconda3/lib/python3.9/site-packages/radian/app.py", line 205, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/home/shpc_100539/miniconda3/lib/python3.9/site-packages/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: libreadline.so.6: cannot open shared object file: No such file or directory

I have tried 
ln -s miniconda/lib/miniconda3/lib/libreadline.so.8.1 miniconda/lib/miniconda3/lib/libreadline.so.6
But there is another error message：

Traceback (most recent call last):
  File "/home/shpc_100539/miniconda3/bin/radian", line 8, in <module>
    sys.exit(main())
  File "/home/shpc_100539/miniconda3/lib/python3.9/site-packages/radian/app.py", line 108, in main
    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)
  File "/home/shpc_100539/miniconda3/lib/python3.9/site-packages/radian/app.py", line 205, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/home/shpc_100539/miniconda3/lib/python3.9/site-packages/rchitect/setup.py", line 48, in init
    raise Exception(load_symbol_error())
Exception: Cannot load symbol R_ParseEvalString: /home/shpc_100539/miniconda3/lib/R/lib/libR.so: undefined symbol: R_ParseEvalString

Has anyone made the same mistake, and has it been solved？

**Comment by Lao-Tz** [comment]
When change my operating system from Windows10 to Ubuntu,I spend a week solved lot of env problems.It contains your problem.
1.Find the place of libreadline.so.6
`locate libreadline.so.6`
2.Add it to ~/.bashrc
`LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/<your path>
export LD_LIBRARY_PATH`
3.source ~/.bashrc
I am new,the error is seems function needs to dynamically link to file.so,we need to appoint env variable LD_LIBRARY_PATH if the file.so not in /lib or /usr/lib.Hope to help you.
