### ISSUE TITLE
Radian tries to link against fixed version of glibcxx

### ISSUE THREAD

**Issue by david-cortes** [randy3k/radian#375]
I get this error when trying to load radian, either through a `pip` or `conda` install:
```
Traceback (most recent call last):
  File "/home/david/anaconda3/bin/radian", line 10, in <module>
    sys.exit(main())
  File "/home/david/anaconda3/lib/python3.9/site-packages/radian/__init__.py", line 108, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/home/david/anaconda3/lib/python3.9/site-packages/radian/radianapp.py", line 96, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/home/david/anaconda3/lib/python3.9/site-packages/rchitect/setup.py", line 46, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: /home/david/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/x86_64-linux-gnu/libicuuc.so.71)
```

Here's an explanation of why this error happens: https://github.com/microsoft/LightGBM/issues/5106#issuecomment-1121925896

Can be worked around by launching it with `LD_PRELOAD="${LD_PRELOAD}:/usr/lib/x86_64-linux-gnu/libstdc++.so.6" radian`, but this should be possible to fix by changing the setup logic.

**Comment by randy3k** [comment]
Likely because your anaconda build was built from a different version of libc.

**Comment by david-cortes** [comment]
> Likely because your anaconda build was built from a different version of libc than what the R build is.

Still happens with `pip` installs.
