### ISSUE TITLE
[Errno 22] Invalid argument on starting Radian on pre-10.6.8 macOS

### ISSUE THREAD

**Issue by barracuda156** [randy3k/radian#403]
```
36-154:~ svacchanda$ radian
R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Platform: powerpc-apple-darwin10.0.0d2 (32-bit)

unexpected error was caught.
please report to https://github.com/randy3k/radian for such error.
[Errno 22] Invalid argument
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '0 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/radian/console.py", line 98, in _read_console
    text = session.prompt(add_history=add_history)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/radian/prompt_session.py", line 72, in prompt
    text = super().prompt(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/radian/lineedit/prompt.py", line 226, in prompt
    result = super().prompt(**kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1034, in prompt
    return self.app.run(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 978, in run
    return loop.run_until_complete(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 885, in run_async
    return await _run_async(f)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 737, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prompt_toolkit/input/vt100.py", line 176, in _attached_input
    loop.add_reader(fd, callback_wrapper)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 331, in add_reader
    self._add_reader(fd, callback, *args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 258, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prompt_toolkit/eventloop/inputhook.py", line 91, in register
    return self.selector.register(fileobj, events, data=data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/selectors.py", line 523, in register
    self._selector.control([kev], 0, 0)
OSError: [Errno 22] Invalid argument
```

**Comment by randy3k** [comment]
It seems to be an issue of upstream `prompt_toolkit`. Not sure how it happened though.

**Comment by barracuda156** [comment]
> It seems to be an issue of upstream `prompt_toolkit`. Not sure how it happened though.

@randy3k Turned out it is a bug in Python itself: https://trac.macports.org/ticket/67046
No solution so far :(

**Comment by barracuda156** [comment]
@randy3k Turns out that w/e the bug was, it has been fixed in 10.6.x. Since we got 10.6.8 running on PowerPC natively now, `radian` launches normally:

![image](https://github.com/user-attachments/assets/b62e6359-4b54-4cf8-b70a-7ee99f5f21a3)

P. S. It will not work on pre-release versions of 10.6 (10a190). It should work on 10.6.8, both Rosetta and natively.
