### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 33: invalid continuation byte

### ISSUE THREAD

**Issue by kebuAAA** [randy3k/radian#438]
when run radian in windows 11 by Python 3.10
throw:
```python
Traceback (most recent call last):
  File "c:\Users\lm\AppData\Local\Programs\Python\Python310\Lib\site-packages\radian\__main__.py", line 31, in <module>
    main(cleanup=cleanup)
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\radian\app.py", line 108, in main
    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\radian\app.py", line 217, in run
    rutils.source_radian_profile(options.profile)
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\radian\rutils.py", line 70, in source_radian_profile
    global_profile = user_path(".radian_profile")
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\radian\rutils.py", line 44, in user_path
    return make_path(rcopy(rcall(("base", "path.expand"), "~")), *args)
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\rchitect\dispatch.py", line 53, in __call__
    return func(*args, **kwargs)
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\rchitect\interface.py", line 581, in rcopy
    return rcopy(unbox(r))
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\rchitect\dispatch.py", line 53, in __call__
    return func(*args, **kwargs)
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\rchitect\interface.py", line 569, in rcopy
    return rcopy(T, s)
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\rchitect\dispatch.py", line 53, in __call__
    return func(*args, **kwargs)
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\rchitect\interface.py", line 479, in rcopy
    return _string(lib.STRING_ELT(s, 0))
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\rchitect\interface.py", line 469, in _string
    return text_type(ffi.string(lib.Rf_translateCharUTF8(s)).decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 33: invalid continuation byte
```
My R version is 4.3.1 and I'm not sure why this problem happened.

**Comment by kebuAAA** [comment]
I solved this problem with the guidance in readme. So sorry to bother you.

**Comment by kebuAAA** [comment]
This [setting](https://github.com/randy3k/radian/issues/269#issuecomment-814468231) worked well but it conflicts with my zip.exe. After checking the `Beta: Use Unicode UTF-8 for worldwide language support`, I will see some garbage characters of file name in my zip file. So I just wonder if there is any otrher solution to deal with this problem.

**Comment by randy3k** [comment]
What version of radian are you using?

**Comment by mqdw222** [comment]
how to solve this problem？help！help！

**Comment by kebuAAA** [comment]
> how to solve this problem？help！help！

Are you sure you meet the same problem with me? If so, solutions may be:
* Change the defalult locale in your computer just as the [readme](https://github.com/randy3k/radian/issues/269#issuecomment-814468231)  does. Changing the system locale or checking the `Beta: Use Unicode UTF-8 for worldwide language support` can solve this problem(My original locale is simplified Chinese).
* adding a new .radian_profile in the `%USERPROFILE%` to avoid stepping into the elif statement in [rutils.py](https://github.com/randy3k/radian/blob/fb643c4c4dad33aa674eb09407c0caa6e41c2d42/radian/rutils.py#L70C1-L71C1)

**Comment by randy3k** [comment]
Um, I believe that for some reason, `user_path(".radian_profile")` or `base::path.expand("~")` has returned a non-utf8 string despite utf-8 locale should have [set](https://github.com/randy3k/radian/blob/fb643c4c4dad33aa674eb09407c0caa6e41c2d42/radian/app.py#L227) earlier.

I will be great if you could test if `rutils.set_locale` is doing its job.
