### ISSUE TITLE
ubuntu 23: radian fails to start

### ISSUE THREAD

**Issue by fpcarv** [randy3k/radian#467]
Hi!

After installing successfully the radian package it fails to start saying that it can't find libR.so  ...

------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/francis/.local/bin/radian", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/francis/.local/lib/python3.11/site-packages/radian/app.py", line 121, in main
    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)
  File "/home/francis/.local/lib/python3.11/site-packages/radian/app.py", line 218, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/usr/local/lib/python3.11/dist-packages/rchitect/setup.py", line 49, in init
    raise Exception(load_lib_error())
Exception: Cannot load shared library: /usr/local/lib/R/lib/libR.so: undefined symbol: u_versionToString_70
------------------------------------------------------------------------------------------------

However libR.so is there, at the place radian says it's looking for it:

$ ls -l /usr/local/lib/R/lib/libR.so
-rwxr-xr-x 1 root root 13267328 fev  4  2023 /usr/local/lib/R/lib/libR.so

Am I doing something wrong?

Thanks for any help!

-Francisco

**Comment by randy3k** [comment]
It is a rpath issue of your libR.  For some reasons, radian seems to fail to set the correct ldpaths to discover the dependencies needed. Could you show the results of `ldd  libR.so`?

**Comment by fpcarv** [comment]
Here it is ...

$ ldd /usr/local/lib/R/lib/libR.so

        linux-vdso.so.1 (0x00007ffc9c5c2000)
        libRblas.so => not found
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f38b1515000)
        libreadline.so.8 => /lib/x86_64-linux-gnu/libreadline.so.8 (0x00007f38b14c1000)
        libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f38b1426000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f38b13f4000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f38b13e1000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f38b13c2000)
        libtirpc.so.3 => /lib/x86_64-linux-gnu/libtirpc.so.3 (0x00007f38b1395000)
        libicuuc.so.70 => /lib/x86_64-linux-gnu/libicuuc.so.70 (0x00007f38b119a000)
        libicui18n.so.70 => /lib/x86_64-linux-gnu/libicui18n.so.70 (0x00007f38b0e00000)
        libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f38b1147000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f38b0a00000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f38b1afc000)
        libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f38b0dcc000)
        libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f38b0d78000)
        libicudata.so.71 => /lib/x86_64-linux-gnu/libicudata.so.71 (0x00007f38aec00000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f38ae800000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f38b0d54000)
        libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f38b0c8b000)
        libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f38b0c5f000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f38b1ac9000)
        libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f38b113a000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f38b1131000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f38b0c4d000)

$ ldd libR.so 
 ldd: ./libR.so: Ficheiro ou pasta inexistente (file does not exist)
