### ISSUE TITLE
Radian console not starting (TypeError in PromptSession.prompt())

### ISSUE THREAD

**Issue by asatzger** [randy3k/radian#473]
Radian console does not start and returns the following error (Windows 11, R 4.3.1, Python 3.10.8):
```
$ radian
R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"
Platform: x86_64-w64-mingw32 (64-bit)
unexpected error was caught.
please report to https://github.com/randy3k/radian for such error.
PromptSession.prompt() got an unexpected keyword argument 'inputhook'
Traceback (most recent call last):
  File "C:\Program Files\Python3.10.8\lib\site-packages\radian\console.py", line 99, in _read_console  
    text = session.prompt(add_history=add_history)
  File "C:\Program Files\Python3.10.8\lib\site-packages\radian\prompt_session.py", line 71, in prompt  
    text = super().prompt(*args, **kwargs)
  File "C:\Program Files\Python3.10.8\lib\site-packages\radian\lineedit\prompt.py", line 228, in prompt
    result = super().prompt(inputhook=self._inputhook, **kwargs)
TypeError: PromptSession.prompt() got an unexpected keyword argument 'inputhook'
```

**Comment by randy3k** [comment]
It seems that you have a incorrect version of prompt-toolkit installed. Please try reinstalling radian.
