### ISSUE TITLE
Tests fail with prompt_toolkit import error

### ISSUE THREAD

**Issue by mschubert** [randy3k/radian#80]
I get the following error when running `python setup.py test`:

```python
running build_ext
prompt (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: prompt (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: prompt
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/mschu/Code/PKGBUILDs/radian/src/radian-0.3.2/radian/prompt.py", line 9, in <module>
    from lineedit import Mode, ModalPromptSession, ModalInMemoryHistory, ModalFileHistory
  File "/usr/lib/python3.7/site-packages/lineedit/__init__.py", line 5, in <module>
    from .prompt import Mode, ModalPromptSession  # noqa
  File "/usr/lib/python3.7/site-packages/lineedit/prompt.py", line 13, in <module>
    from prompt_toolkit.shortcuts.prompt import _true, CompleteStyle
ImportError: cannot import name '_true' from 'prompt_toolkit.shortcuts.prompt'
          (/usr/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py)
```

This is using `radian=0.3.2`, `python=3.7.2`, `lineedit=0.1.1`, `prompt_toolkit=2.0.8`.

**Comment by randy3k** [comment]
Not sure why `python setup.py` failed, but the test could be run by `pytest`.

```
(randyimac)-radian$ pytest                                                                                                                           (master) 
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.6.2, pytest-4.0.2, py-1.7.0, pluggy-0.8.0
rootdir: /Users/Randy/Dropbox/R/radian, inifile: setup.cfg
collected 1 item                                                                                                                                             

tests/test_startup.py .                                                                                                                                [100%]

================================================================== 1 passed in 2.65 seconds ==================================================================
(randyimac)-radian$                                                                                                                                  (master) 
```

**Comment by randy3k** [comment]
I might just need to follow this: https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner

**Comment by randy3k** [comment]
fixed at master.
