### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by t-kalinowski** [randy3k/radian#86]
```python
> radian
Traceback (most recent call last):
  File "/home/me/.local/bin/radian", line 10, in <module>
  sys.exit(main())
File "/home/me/.local/lib/python2.7/site-packages/radian/__init__.py", line 74, in main
RadianApplication(r_home, ver=__version__).run(options)
File "/home/me/.local/lib/python2.7/site-packages/radian/radianapp.py", line 150, in run
self.set_env_vars(options)
File "/home/me/.local/lib/python2.7/site-packages/radian/radianapp.py", line 139, in set_env_vars
except (FileNotFoundError, subprocess.CalledProcessError):
  NameError: global name 'FileNotFoundError' is not defined
```

**Comment by randy3k** [comment]
Thanks for the report. It is largely due to radian cannot locate R, or the libR.so. These error is a python 2.7 specific error.

**Comment by t-kalinowski** [comment]
Thanks, that's helpful. I tried 
```
LD_LIBRARY_PATH=/usr/lib/R/lib:$LD_LIBRARY_PATH radian
```
but it gives the same error message. Do you have any suggestions?

**Comment by t-kalinowski** [comment]
Thanks, that's helpful. I tried 
``` 
LD_LIBRARY_PATH=/usr/lib/R/lib:$LD_LIBRARY_PATH radian
```
but still got the same error message. Do you have any suggestions?

**Comment by randy3k** [comment]
Was your R compiled with shared library?

**Comment by t-kalinowski** [comment]
I believe so. Its the standard in ubuntu 18 that you get (once you enable the 3.5 repo)

**Comment by randy3k** [comment]
Could you report `radian -v` and `R --slave -e "R.home('lib')"`?

**Comment by t-kalinowski** [comment]
``` 
> radian -v
radian version: 0.3.3
r executable: /usr/lib/R/bin/R
r version: 3.5.2
python executable: /usr/bin/python2
python version: 2.7.15
> R --slave -e "R.home('lib')"
[1] "/usr/lib/R/lib"

**Comment by randy3k** [comment]
I figured the issue and it has been fixed now. A new release is on the way.

**Comment by t-kalinowski** [comment]
Thank you!
