### ISSUE TITLE
Symbol not found: ___addtf3

### ISSUE THREAD

**Issue by intheravine** [randy3k/radian#94]
I'd like to run radian but I'm getting this error on one of my macs (mac os x 10.14.4) and so far I haven't been able to find a way to resolve it.
```
~% radian
Traceback (most recent call last):
  File "/usr/local/bin/radian", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/radian/__init__.py", line 74, in main
    RadianApplication(r_home, ver=__version__).run(options)
  File "/usr/local/lib/python3.7/site-packages/radian/radianapp.py", line 175, in run
    self.rs = RSession(set_default_callbacks=False, verbose=options.debug)
  File "/usr/local/lib/python3.7/site-packages/rchitect/bootstrap.py", line 257, in __init__
    libR = load_libR(rhome)
  File "/usr/local/lib/python3.7/site-packages/rchitect/utils.py", line 74, in load_libR
    return PyDLL(str(libRpath), mode=RTLD_GLOBAL)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 10): Symbol not found: ___addtf3
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libquadmath.0.dylib
  Expected in: /usr/local/lib/libgcc_s.1.dylib
 in /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libquadmath.0.dylib
```

**Comment by randy3k** [comment]
What version of R are you using?

**Comment by intheravine** [comment]
3.6.0

**Comment by randy3k** [comment]
It seems that it’s an issue of the version the libgcc. This post has explained the issue in detail https://github.com/citwild/laugh-finder/issues/11

**Comment by randy3k** [comment]
It’s not an issue of radian per se, but an issue of brewed python and gcc.

**Comment by intheravine** [comment]
Hmm - I'm not sure why my /usr/local/lib/libgcc_s.1.dylib was from 2008 and was not updated with updates to my machine. I updated it by hand - hopefully I haven't messed something else up but now radian works.
